import { Button } from "@/components/ui/button";
import ProductCard from "@/components/ProductCard";
import StorefrontLayout from "@/components/StorefrontLayout";
import { BreadCrumbs, EmptyState } from "@/components/CommerceUI";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Slider } from "@/components/ui/slider";
import type { StoreProduct } from "@/lib/store";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, ArrowRight, Grid2X2, LayoutList } from "lucide-react";
import { useMemo, useState } from "react";
import { Link, useLocation } from "wouter";

function useSearchParams() { return new URLSearchParams(window.location.search); }
export default function Catalog({ mode = "shop" }: { mode?: "shop" | "search" | "collection" | "brand" | "categories" | "brands" }) {
  const [location, setLocation] = useLocation();
  const params = useSearchParams();
  const initialQuery = params.get("q") || "";
  const collectionSlug = mode === "collection" ? window.location.pathname.split("/").at(-1) : undefined;
  const brandSlug = mode === "brand" ? window.location.pathname.split("/").at(-1) : undefined;
  const [query, setQuery] = useState(initialQuery);
  const [sort, setSort] = useState<"featured" | "newest" | "price-asc" | "price-desc" | "name">((params.get("sort") as "featured" | "newest" | "price-asc" | "price-desc" | "name") || "featured");
  const [selectedBrand, setSelectedBrand] = useState(brandSlug || "");
  const [range, setRange] = useState([0, 10000]);
  const [view, setView] = useState<"grid" | "list">("grid");
  const [page, setPage] = useState(Math.max(1, Number(params.get("page")) || 1));
  const input = useMemo(() => ({ query: query || undefined, categorySlug: collectionSlug, brandSlug: selectedBrand || undefined, minPrice: range[0] || undefined, maxPrice: range[1] < 10000 ? range[1] : undefined, sort, page, pageSize: 12 }), [query, collectionSlug, selectedBrand, range, sort, page]);
  const catalog = trpc.catalog.list.useQuery(input);
  const brands = trpc.catalog.brands.useQuery();
  const categories = trpc.catalog.categories.useQuery();
  const collection = categories.data?.find(item => item.slug === collectionSlug);
  const brand = brands.data?.find(item => item.slug === brandSlug);
  const title = mode === "search" ? `Search results${initialQuery ? ` for “${initialQuery}”` : ""}` : mode === "collection" ? collection?.name || "Collection" : mode === "brand" ? brand?.name || "Brand" : mode === "categories" ? "Shop by intention" : mode === "brands" ? "Brands we select" : "The collection";
  const description = mode === "search" ? "A focused set of matching automotive essentials." : mode === "categories" ? "Explore the collection from the point of view that matters to your next drive." : mode === "brands" ? "A concise edit of specialist makers and thoughtful in-house essentials." : collection?.description || brand?.description || "Everything useful for a more considered vehicle.";
  const clearFilters = () => { setQuery(""); setSelectedBrand(brandSlug || ""); setRange([0, 10000]); setSort("featured"); setPage(1); if (mode === "search") setLocation("/search"); };
  const updateQuery = (value: string) => { setQuery(value); setPage(1); if (mode === "search") setLocation(value ? `/search?q=${encodeURIComponent(value)}` : "/search"); };
  const directory = mode === "categories" ? categories.data?.map(item => ({ id: item.id, name: item.name, slug: item.slug, description: item.description || "Considered essentials selected for the road ahead.", image: item.imageUrl, href: `/collections/${item.slug}` })) : mode === "brands" ? brands.data?.map(item => ({ id: item.id, name: item.name, slug: item.slug, description: item.description || "Specialist automotive essentials selected by AutoGear.", image: item.logoUrl, href: `/brands/${item.slug}` })) : null;
  const totalPages = Math.max(1, Math.ceil((catalog.data?.total || 0) / (catalog.data?.pageSize || 12)));
  if (directory) return <StorefrontLayout><div className="container py-8 sm:py-12"><BreadCrumbs items={[{ label: "Home", href: "/" }, { label: title }]} /><div className="max-w-2xl"><p className="eyebrow">Explore AutoGear</p><h1 className="page-title">{title}</h1><p className="mt-3 text-sm leading-6 text-muted-foreground sm:text-base">{description}</p></div><div className="mt-9 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{directory.map(item => <Link href={item.href} key={item.id} className="group relative min-h-64 overflow-hidden rounded-[1.5rem] bg-[#172030] p-6 text-white"><img src={item.image || "/manus-storage/category-utility_fa340543.jpg"} alt="" className="absolute inset-0 h-full w-full object-cover opacity-45 transition duration-500 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-[#101825] via-[#101825]/50 to-transparent" /><div className="relative flex h-full flex-col justify-end"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#d2ae68]">{mode === "brands" ? "View brand" : "View collection"}</p><p className="mt-2 font-display text-3xl font-bold tracking-[-.04em]">{item.name}</p><p className="mt-2 max-w-xs text-sm leading-5 text-slate-200">{item.description}</p></div></Link>)}</div></div></StorefrontLayout>;
  return <StorefrontLayout><div className="container py-8 sm:py-12"><BreadCrumbs items={[{ label: "Home", href: "/" }, { label: mode === "search" ? "Search" : "Shop", href: "/shop" }, ...(mode === "collection" || mode === "brand" ? [{ label: title }] : [])]} /><div className="max-w-2xl"><p className="eyebrow">{mode === "search" ? "Search the collection" : mode === "brand" ? "Brand edit" : "Shop AutoGear"}</p><h1 className="page-title">{title}</h1><p className="mt-3 text-sm leading-6 text-muted-foreground sm:text-base">{description}</p></div>
    <div className="mt-9 grid gap-8 lg:grid-cols-[15.5rem_1fr]">
      <aside className="rounded-[1.3rem] border border-border bg-card p-5 lg:sticky lg:top-24 lg:h-fit"><div className="mb-5 flex items-center justify-between"><p className="font-bold">Refine</p><button className="text-xs font-semibold text-muted-foreground hover:text-foreground" onClick={clearFilters}>Reset</button></div>
        <div className="space-y-6"><div><Label htmlFor="product-search" className="text-xs font-bold uppercase tracking-[.12em] text-muted-foreground">Search</Label><Input id="product-search" className="mt-2 rounded-xl" value={query} onChange={event => updateQuery(event.target.value)} placeholder="Name or SKU" /></div>
        {mode !== "collection" && <div><p className="text-xs font-bold uppercase tracking-[.12em] text-muted-foreground">Category</p><div className="mt-3 grid gap-2">{categories.data?.map(item => <button key={item.id} className="text-left text-sm text-muted-foreground transition hover:text-foreground" onClick={() => setLocation(`/collections/${item.slug}`)}>{item.name}</button>)}</div></div>}
        {mode !== "brand" && <div><p className="text-xs font-bold uppercase tracking-[.12em] text-muted-foreground">Brand</p><div className="mt-3 grid gap-2">{brands.data?.map(item => <label className="flex cursor-pointer items-center gap-2 text-sm text-muted-foreground" key={item.id}><Checkbox checked={selectedBrand === item.slug} onCheckedChange={() => { setSelectedBrand(selectedBrand === item.slug ? "" : item.slug); setPage(1); }} />{item.name}</label>)}</div></div>}
        <div><div className="flex items-center justify-between"><p className="text-xs font-bold uppercase tracking-[.12em] text-muted-foreground">Price range</p><span className="text-xs font-semibold text-primary">PKR {range[0].toLocaleString()}–{range[1].toLocaleString()}+</span></div><Slider className="mt-4" min={0} max={10000} step={250} value={range} onValueChange={next => { setRange(next); setPage(1); }} /></div></div>
      </aside>
      <section><div className="mb-5 flex flex-col gap-3 rounded-xl border border-border/80 bg-secondary/35 p-3 sm:flex-row sm:items-center sm:justify-between"><p className="text-sm text-muted-foreground">{catalog.isLoading ? "Updating collection…" : `${catalog.data?.total ?? 0} pieces found`}</p><div className="flex items-center justify-between gap-2"><Select value={sort} onValueChange={value => { setSort(value as typeof sort); setPage(1); }}><SelectTrigger className="h-9 w-[10.5rem] rounded-lg bg-background text-xs"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="featured">Featured</SelectItem><SelectItem value="newest">Newest</SelectItem><SelectItem value="price-asc">Price: low to high</SelectItem><SelectItem value="price-desc">Price: high to low</SelectItem><SelectItem value="name">Name</SelectItem></SelectContent></Select><div className="hidden rounded-lg border border-border bg-background p-0.5 sm:flex"><button onClick={() => setView("grid")} className={`grid h-8 w-8 place-items-center rounded-md ${view === "grid" ? "bg-secondary text-foreground" : "text-muted-foreground"}`} aria-label="Grid view"><Grid2X2 className="h-4 w-4" /></button><button onClick={() => setView("list")} className={`grid h-8 w-8 place-items-center rounded-md ${view === "list" ? "bg-secondary text-foreground" : "text-muted-foreground"}`} aria-label="List view"><LayoutList className="h-4 w-4" /></button></div></div></div>
        {catalog.isLoading ? <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{Array.from({ length: 9 }).map((_, i) => <div className="h-[22rem] animate-pulse rounded-[1.3rem] bg-secondary" key={i} />)}</div> : !catalog.data?.products.length ? <EmptyState title="Nothing quite matched." text="Try widening your price range or removing a filter to see more of the collection." action={{ label: "Browse all products", href: "/shop" }} /> : <><div className={view === "grid" ? "grid gap-4 sm:grid-cols-2 xl:grid-cols-3" : "grid gap-3"}>{(catalog.data.products as StoreProduct[]).map(product => <ProductCard key={product.id} product={product} list={view === "list"} />)}</div>{totalPages > 1 && <div className="mt-8 flex items-center justify-center gap-3"><button disabled={page === 1} onClick={() => setPage(current => Math.max(1, current - 1))} className="inline-flex h-10 items-center gap-2 rounded-full border border-border px-4 text-sm font-bold disabled:cursor-not-allowed disabled:opacity-40"><ArrowLeft className="h-4 w-4" />Previous</button><p className="text-sm text-muted-foreground">Page {page} of {totalPages}</p><button disabled={page === totalPages} onClick={() => setPage(current => Math.min(totalPages, current + 1))} className="inline-flex h-10 items-center gap-2 rounded-full border border-border px-4 text-sm font-bold disabled:cursor-not-allowed disabled:opacity-40">Next<ArrowRight className="h-4 w-4" /></button></div>}</>}
      </section>
    </div></div></StorefrontLayout>;
}
