import { Button } from "@/components/ui/button";
import ProductCard from "@/components/ProductCard";
import StorefrontLayout from "@/components/StorefrontLayout";
import { SectionHeading } from "@/components/CommerceUI";
import { heroImage, promoImage, type StoreCategory, type StoreProduct } from "@/lib/store";
import { trpc } from "@/lib/trpc";
import { ArrowRight, CheckCircle2, Headphones, ShieldCheck, Sparkles, Truck } from "lucide-react";
import { Link } from "wouter";

const featurePoints = [
  { icon: ShieldCheck, title: "Useful by design", text: "A focused edit of everyday automotive essentials." },
  { icon: Truck, title: "Clear delivery", text: "Straightforward shipping from cart to doorstep." },
  { icon: Headphones, title: "Human help", text: "Practical answers when you need them." },
];
const fallbackCategories: StoreCategory[] = [
  { id: 1, name: "Car Care", slug: "car-care", description: "Keep the finish, cabin and details in good order.", imageUrl: "/manus-storage/category-detailing_2f0366b5.jpg", isFeatured: true, sortOrder: 1 },
  { id: 2, name: "Interior", slug: "cabin-comfort", description: "Small upgrades for the part of the car you live in.", imageUrl: "/manus-storage/category-interior_d5e055da.jpg", isFeatured: true, sortOrder: 2 },
  { id: 3, name: "Roadside Utility", slug: "roadside-utility", description: "Prepared essentials for the miles ahead.", imageUrl: "/manus-storage/category-utility_fa340543.jpg", isFeatured: true, sortOrder: 3 },
];

function ProductRow({ items }: { items: StoreProduct[] }) {
  return <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{items.map(product => <ProductCard key={product.id} product={product} />)}</div>;
}

export default function Home() {
  const categories = trpc.catalog.categories.useQuery();
  const featured = trpc.catalog.featured.useQuery();
  const newArrivals = trpc.catalog.newArrivals.useQuery();
  const categoryItems = (categories.data?.filter(item => item.isFeatured).slice(0, 3) || fallbackCategories) as StoreCategory[];
  return <StorefrontLayout>
    <section className="hero-shell"><img src={heroImage} alt="A graphite vehicle in a dramatic mountain setting" loading="eager" decoding="async" fetchPriority="high" className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(12,18,29,.94)_2%,rgba(12,18,29,.65)_46%,rgba(12,18,29,.12)_84%)]" /><div className="container relative z-10 flex min-h-[36rem] items-center py-16 sm:min-h-[41rem]"><div className="max-w-xl text-[#f8f5ee]"><p className="mb-5 flex items-center gap-2 text-xs font-bold uppercase tracking-[.22em] text-[#d6b777]"><span className="roadline" />Zalim Marketing</p><h1 className="max-w-lg font-display text-5xl font-bold leading-[.95] tracking-[-.06em] sm:text-7xl">Make every drive easier.</h1><p className="mt-6 max-w-md text-base leading-7 text-slate-200">A focused marketplace for the car-care, cabin and roadside pieces that make the everyday vehicle feel more sorted.</p><div className="mt-8 flex flex-wrap gap-3"><Button asChild size="lg" className="rounded-full bg-[#d2ae68] px-6 text-[#131a26] hover:bg-[#e4c583]"><Link href="/shop">Shop all essentials <ArrowRight className="ml-2 h-4 w-4" /></Link></Button><Button asChild size="lg" variant="outline" className="rounded-full border-white/30 bg-white/5 px-6 text-white hover:bg-white/15 hover:text-white"><Link href="/vehicle-finder">Find for your vehicle</Link></Button></div></div></div></section>
    <section className="container relative z-20 -mt-9 pb-5"><div className="grid gap-4 rounded-[1.45rem] border border-white/15 bg-[#f7f4ee]/95 p-5 shadow-[0_18px_40px_-28px_rgba(0,0,0,.55)] backdrop-blur sm:grid-cols-[1fr_auto] sm:items-center sm:p-6"><div className="flex gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-primary/10 text-primary"><Sparkles className="h-5 w-5" /></div><div><p className="font-bold tracking-tight">Start with your vehicle.</p><p className="mt-1 text-sm text-muted-foreground">Use the vehicle finder to organise your search, then check each product’s fit notes.</p></div></div><Button asChild variant="outline" className="rounded-full"><Link href="/vehicle-finder">Open vehicle finder <ArrowRight className="ml-2 h-4 w-4" /></Link></Button></div></section>
    <section className="container py-10"><div className="grid gap-px overflow-hidden rounded-[1.5rem] border border-border bg-border md:grid-cols-3">{featurePoints.map(({ icon: Icon, title, text }) => <div key={title} className="flex gap-4 bg-background px-6 py-6"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-primary/10 text-primary"><Icon className="h-5 w-5" /></div><div><p className="font-bold tracking-tight">{title}</p><p className="mt-1 text-sm leading-5 text-muted-foreground">{text}</p></div></div>)}</div></section>
    <section className="container py-11"><SectionHeading eyebrow="Popular sections" title="Browse the garage" text="Find a starting point, then use product detail pages to check specifications and compatibility." /><div className="grid gap-4 md:grid-cols-3">{categoryItems.map((category, index) => <Link href={`/collections/${category.slug}`} key={category.id} className="category-card group"><img src={category.imageUrl || fallbackCategories[index % fallbackCategories.length].imageUrl!} alt="" loading="lazy" decoding="async" className="lazy-media absolute inset-0 h-full w-full object-cover transition duration-700 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-[#111722]/90 via-[#111722]/15 to-transparent" /><div className="relative mt-auto p-6 text-white"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#e4c783]">Browse category</p><p className="mt-2 text-2xl font-bold tracking-tight">{category.name}</p><p className="mt-1 text-sm text-slate-200">{category.description}</p><span className="mt-5 inline-flex items-center gap-1 text-sm font-bold">Explore <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1" /></span></div></Link>)}</div></section>
    <section className="container py-12"><SectionHeading eyebrow="Popular right now" title="High-use essentials" text="Useful objects for cleaner cabins, safer stops and better everyday upkeep." action={{ label: "View all products", href: "/shop?sort=featured" }} />{featured.isLoading ? <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{Array.from({ length: 4 }).map((_, i) => <div key={i} className="h-[22rem] animate-pulse rounded-[1.35rem] bg-secondary" />)}</div> : <ProductRow items={(featured.data || []) as StoreProduct[]} />}</section>
    <section className="container py-8"><div className="relative overflow-hidden rounded-[2rem] bg-[#151d2b] px-7 py-12 sm:px-12 sm:py-16"><img src={promoImage} alt="A dark blue vehicle inside a warm contemporary workshop" loading="lazy" decoding="async" className="lazy-media absolute inset-0 h-full w-full object-cover opacity-55" /><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(17,24,39,.98)_5%,rgba(17,24,39,.78)_43%,rgba(17,24,39,.16)_100%)]" /><div className="relative max-w-lg text-white"><p className="eyebrow text-[#e1be77]">Pack smart, drive prepared</p><h2 className="mt-3 font-display text-4xl font-bold leading-[1.02] tracking-[-.05em] sm:text-5xl">Roadside essentials, without the excess.</h2><p className="mt-5 max-w-md text-sm leading-7 text-slate-200">Compact, dependable tools selected for the moments where being prepared makes the difference.</p><Button asChild className="mt-7 rounded-full bg-[#d2ae68] text-[#131a26] hover:bg-[#e4c583]"><Link href="/collections/roadside-utility">Browse roadside utility <ArrowRight className="ml-2 h-4 w-4" /></Link></Button></div></div></section>
    <section className="container py-12"><SectionHeading eyebrow="Fresh to the marketplace" title="New additions" text="The newest practical entries in the Zalim Marketing edit." action={{ label: "See new arrivals", href: "/shop?sort=newest" }} />{newArrivals.isLoading ? <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{Array.from({ length: 4 }).map((_, i) => <div key={i} className="h-[22rem] animate-pulse rounded-[1.35rem] bg-secondary" />)}</div> : <ProductRow items={(newArrivals.data || []) as StoreProduct[]} />}</section>
    <section className="container pb-2"><div className="grid gap-9 rounded-[1.8rem] bg-[#f0ebe1] p-8 md:grid-cols-[1fr_1.3fr] md:p-12"><div><p className="eyebrow">The Zalim approach</p><h2 className="mt-3 font-display text-4xl font-bold tracking-[-.05em] text-[#111722]">Good details stay useful.</h2></div><div className="grid gap-4 sm:grid-cols-2">{["Clear specifications, so the detail is never hidden.", "Original catalog curation focused on practical use.", "A calmer shopping experience from discovery to delivery.", "No made-up reviews or noise—just product information."].map(point => <p className="flex gap-2 text-sm leading-6 text-[#46505f]" key={point}><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-primary" />{point}</p>)}</div></div></section>
  </StorefrontLayout>;
}
