import { useAuth } from "@/_core/hooks/useAuth";
import { EmptyState } from "@/components/CommerceUI";
import StorefrontLayout from "@/components/StorefrontLayout";
import { Button } from "@/components/ui/button";
import { formatCurrency } from "@/lib/store";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, MessageCircle, PackageCheck } from "lucide-react";
import { Link } from "wouter";

export default function OrderConfirmation() {
  const { isAuthenticated } = useAuth();
  const orderNumber = new URLSearchParams(window.location.search).get("order") || "";
  const order = trpc.orders.detail.useQuery({ orderNumber }, { enabled: isAuthenticated && Boolean(orderNumber) });
  if (!isAuthenticated) return <StorefrontLayout><main className="container py-16"><section className="mx-auto max-w-2xl border border-slate-200 bg-white p-8 text-center"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#805d1e]">Guest order journey</p><h1 className="mt-3 font-display text-4xl font-bold tracking-[-.055em] text-slate-950">Use the guest basket to create a test order.</h1><p className="mx-auto mt-4 max-w-lg text-sm leading-6 text-slate-600">The public store does not require sign-in. Add products to the guest basket, use the test checkout, and follow the browser-local order-status view.</p><div className="mt-7 flex flex-col justify-center gap-3 sm:flex-row"><Link href="/cart" className="inline-flex h-11 items-center justify-center bg-slate-950 px-5 text-sm font-bold text-white hover:bg-[#b88d3c]">Open guest basket</Link><Link href="/demo-order" className="inline-flex h-11 items-center justify-center border border-slate-300 px-5 text-sm font-bold text-slate-900 hover:border-[#b88d3c]">View test order status</Link></div></section></main></StorefrontLayout>;
  if (order.isLoading) return <StorefrontLayout><main className="container py-14"><div className="mx-auto h-72 max-w-2xl animate-pulse bg-slate-100" /></main></StorefrontLayout>;
  if (!order.data) return <StorefrontLayout><main className="container py-16"><EmptyState title="We could not find that request." text="Return to your account to review your order request history." action={{ label: "View account", href: "/account" }} /></main></StorefrontLayout>;
  const requestStatus = order.data.status === "payment_pending" ? "request received" : order.data.status.replaceAll("_", " ");
  const currency = order.data.currency === "PKR" ? "EUR" : order.data.currency;
  return <StorefrontLayout><main className="container py-12 sm:py-20"><section className="mx-auto max-w-2xl border border-slate-200 bg-white px-6 py-10 text-center sm:px-12"><div className="mx-auto grid h-16 w-16 place-items-center bg-[#f1e5c1] text-[#805d1e]"><CheckCircle2 className="h-8 w-8" /></div><p className="mt-6 eyebrow">Order enquiry · {order.data.orderNumber}</p><h1 className="mt-4 font-display text-5xl font-bold tracking-[-.065em] text-slate-950 sm:text-7xl">Your request is with us.</h1><p className="mx-auto mt-5 max-w-lg text-sm leading-7 text-slate-600">Zalim-Marketing will review the selected items, availability and delivery information, then confirm the next practical step directly with you.</p><div className="mx-auto mt-8 grid max-w-md gap-3 border border-slate-200 bg-[#f5f1e7] p-5 text-left sm:grid-cols-2"><div><p className="text-[10px] font-bold uppercase tracking-[.13em] text-slate-500">Catalogue total</p><p className="mt-1 text-lg font-bold text-slate-950">{formatCurrency(order.data.total, currency)}</p></div><div><p className="text-[10px] font-bold uppercase tracking-[.13em] text-slate-500">Request status</p><p className="mt-1 text-lg font-bold capitalize text-slate-950">{requestStatus}</p></div></div><div className="mx-auto mt-7 grid max-w-md gap-3 text-left"><div className="flex items-start gap-3 border border-slate-200 p-4"><MessageCircle className="mt-0.5 h-5 w-5 shrink-0 text-[#805d1e]" /><div><p className="text-sm font-bold text-slate-950">No payment collected here</p><p className="mt-1 text-xs leading-5 text-slate-600">This is an enquiry-first request. The store will confirm availability and delivery details before any order is agreed.</p></div></div><div className="flex items-start gap-3 border border-slate-200 p-4"><PackageCheck className="mt-0.5 h-5 w-5 shrink-0 text-[#805d1e]" /><div><p className="text-sm font-bold text-slate-950">Keep your vehicle context handy</p><p className="mt-1 text-xs leading-5 text-slate-600">For a vehicle-specific product, be ready to share its make, model and year if the team needs to confirm fit.</p></div></div></div><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><Button asChild className="h-11 rounded-none bg-slate-950 text-white hover:bg-[#b88d3c]"><Link href={`/account/orders/${order.data.orderNumber}`}>View request details</Link></Button><Button asChild variant="outline" className="h-11 rounded-none border-slate-300"><Link href="/shop">Continue browsing</Link></Button></div></section></main></StorefrontLayout>;
}
