import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import StorefrontLayout from "@/components/StorefrontLayout";
import { EmptyState } from "@/components/CommerceUI";
import { formatCurrency } from "@/lib/store";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, PackageCheck, ShieldCheck } from "lucide-react";
import { Link } from "wouter";

export default function OrderConfirmation() {
  const { isAuthenticated } = useAuth();
  const orderNumber = new URLSearchParams(window.location.search).get("order") || "";
  const order = trpc.orders.detail.useQuery({ orderNumber }, { enabled: isAuthenticated && Boolean(orderNumber), refetchInterval: query => query.state.data?.paymentStatus === "paid" ? false : 4000 });
  if (!isAuthenticated) return <StorefrontLayout><div className="container py-16"><EmptyState title="Sign in to view your confirmation." text="We keep order confirmations inside your secure account." action={{ label: "Go to account", href: "/account" }} /></div></StorefrontLayout>;
  if (order.isLoading) return <StorefrontLayout><div className="container py-14"><div className="h-72 animate-pulse rounded-[1.5rem] bg-secondary" /></div></StorefrontLayout>;
  if (!order.data) return <StorefrontLayout><div className="container py-16"><EmptyState title="We could not find that order." text="Return to your account to see your order history and purchase updates." action={{ label: "View account", href: "/account" }} /></div></StorefrontLayout>;
  const paymentConfirmed = order.data.paymentStatus === "paid";
  return <StorefrontLayout><div className="container py-12 sm:py-20"><div className="mx-auto max-w-2xl rounded-[2rem] border border-border bg-card px-6 py-10 text-center shadow-[0_20px_60px_-45px_rgba(15,23,42,.5)] sm:px-12"><div className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-primary/10 text-primary"><CheckCircle2 className="h-8 w-8" /></div><p className="mt-6 eyebrow">Order {order.data.orderNumber}</p><h1 className="mt-3 font-display text-5xl font-bold tracking-[-.06em] text-[#151d2b] sm:text-6xl">Thank you for your order.</h1><p className="mx-auto mt-5 max-w-lg text-sm leading-7 text-muted-foreground">{paymentConfirmed ? "Your card payment has been confirmed and your order is now being prepared." : "Your payment return was received. We are securely confirming the payment and will update this page automatically."}</p><div className="mx-auto mt-8 grid max-w-md gap-3 rounded-[1.25rem] bg-secondary/60 p-5 text-left sm:grid-cols-2"><div><p className="text-[10px] font-bold uppercase tracking-[.13em] text-muted-foreground">Order total</p><p className="mt-1 text-lg font-bold">{formatCurrency(order.data.total, order.data.currency)}</p></div><div><p className="text-[10px] font-bold uppercase tracking-[.13em] text-muted-foreground">Order status</p><p className="mt-1 text-lg font-bold capitalize">{order.data.status.replace("_", " ")}</p></div></div><div className="mx-auto mt-7 grid max-w-md gap-3 text-left"><div className="flex items-start gap-3 rounded-xl border border-border p-4"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-primary" /><div><p className="text-sm font-bold">Payment handled securely</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Your card details are processed by Stripe and are never stored by AutoGear.</p></div></div><div className="flex items-start gap-3 rounded-xl border border-border p-4"><PackageCheck className="mt-0.5 h-5 w-5 shrink-0 text-primary" /><div><p className="text-sm font-bold">A clear order journey</p><p className="mt-1 text-xs leading-5 text-muted-foreground">We’ll email milestones as your order is confirmed, packed and sent out.</p></div></div></div><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><Button asChild className="rounded-full"><Link href={`/account/orders/${order.data.orderNumber}`}>View order details</Link></Button><Button asChild variant="outline" className="rounded-full"><Link href="/shop">Continue shopping</Link></Button></div></div></div></StorefrontLayout>;
}
