import { BreadCrumbs } from "@/components/CommerceUI";
import StorefrontLayout from "@/components/StorefrontLayout";
import { policyContent } from "@/lib/store";
import { ArrowRight, Mail, MessageCircle } from "lucide-react";
import { Link, useLocation } from "wouter";

export default function StaticPage() {
  const [location] = useLocation();
  const slug = location.split("/").filter(Boolean).at(-1) || "about";
  const content = policyContent[slug] || policyContent.about;
  const isContact = slug === "contact";
  const guide = isContact ? ["Share the product name or link", "Include the vehicle make, model and year", "Tell us your preferred delivery location"] : slug === "faq" ? ["Use Vehicle Finder to begin", "Read product dimensions carefully", "Message us if a detail is unclear"] : ["Browse a useful department", "Review details before selecting", "Send an enquiry when the shortlist is ready"];
  return <StorefrontLayout><main className="container py-9 sm:py-14"><BreadCrumbs items={[{ label: "Home", href: "/" }, { label: content.title }]} /><section className="mt-9 grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">{content.eyebrow}</p><h1 className="mt-4 max-w-xl font-display text-5xl font-bold leading-[.9] tracking-[-.065em] text-slate-950 sm:text-7xl">{content.title}</h1><p className="mt-6 max-w-md text-base leading-7 text-slate-600">{content.intro}</p>{isContact ? <div className="mt-8 grid gap-3"><a href="https://wa.me/923255531155" target="_blank" rel="noreferrer" className="flex items-center gap-3 border border-[#b88d3c] bg-[#faf5e7] p-4 text-sm font-bold text-[#76531a] hover:bg-[#f2e4be]"><MessageCircle className="h-5 w-5" />WhatsApp +92 325 5531155</a><a href="mailto:raosaqlaingee@gmail.com" className="flex items-center gap-3 border border-slate-300 p-4 text-sm font-bold text-slate-950 hover:border-slate-950"><Mail className="h-5 w-5" />raosaqlaingee@gmail.com</a></div> : <Link href="/shop" className="mt-8 inline-flex h-11 items-center bg-slate-950 px-5 text-sm font-bold text-white hover:bg-[#b88d3c]">Explore the catalogue <ArrowRight className="ml-2 h-4 w-4" /></Link>}</div><div className="border border-slate-200 bg-[#f5f1e7] p-6 sm:p-10"><div className="space-y-8">{content.sections.map((section, index) => <section key={section.heading} className={index ? "border-t border-[#ddd4c2] pt-8" : ""}><p className="font-display text-3xl font-bold tracking-[-.045em] text-slate-950">{section.heading}</p><p className="mt-3 max-w-xl text-sm leading-7 text-slate-600">{section.body}</p></section>)}</div></div></section><section className="mt-14 border border-slate-200 bg-white p-6 sm:p-9"><div className="flex flex-col gap-4 border-b border-slate-200 pb-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">A clearer next step</p><h2 className="mt-3 font-display text-4xl font-bold leading-[.9] tracking-[-.055em] text-slate-950">Useful guidance, before the road gets complicated.</h2></div><span className="text-5xl font-display font-bold text-[#d6af59]">0{content.sections.length}</span></div><div className="mt-6 grid gap-4 md:grid-cols-3">{guide.map((item, index) => <div key={item} className="border-t-2 border-[#d6af59] bg-[#faf9f6] p-5"><span className="text-[10px] font-bold uppercase tracking-[.14em] text-[#8a6726]">Step 0{index + 1}</span><p className="mt-3 text-sm font-bold leading-6 text-slate-950">{item}</p><p className="mt-2 text-xs leading-5 text-slate-600">Keep the key detail close so Zalim-Marketing can give clearer, more useful guidance.</p></div>)}</div></section></main></StorefrontLayout>;
}
