import { drizzle } from "drizzle-orm/node-postgres";
import pg from "pg";
import { eq } from "drizzle-orm";
import { brands, categories, products } from "../drizzle/schema.ts";

if (!process.env.DATABASE_URL) throw new Error("DATABASE_URL is required to seed the catalog.");

const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } });
const db = drizzle(pool);
const media = {
  detailing: "/manus-storage/category-detailing_2f0366b5.jpg",
  interior: "/manus-storage/category-interior_d5e055da.jpg",
  utility: "/manus-storage/category-utility_fa340543.jpg",
  inflator: "/manus-storage/product-orbit-inflator_5d9564fd.jpg",
  detailKit: "/manus-storage/product-sierra-detail-kit_30c89008.jpg",
  organizer: "/manus-storage/product-atlas-organizer_955f56bc.jpg",
  mount: "/manus-storage/product-velar-mount_85a6698c.jpg",
  light: "/manus-storage/product-nova-light_24e6c57b.jpg",
};

const categoryRows = [
  { name: "Car Care", slug: "car-care", description: "Washing, detailing and seasonal protection for everyday cars and weekend projects.", imageUrl: media.detailing, isFeatured: true, sortOrder: 1 },
  { name: "Interior & Comfort", slug: "cabin-comfort", description: "Useful cabin storage, cleaning and travel upgrades for every drive.", imageUrl: media.interior, isFeatured: true, sortOrder: 2 },
  { name: "Safety & Utility", slug: "roadside-utility", description: "Roadside, boot and touring essentials for real-world preparedness.", imageUrl: media.utility, isFeatured: true, sortOrder: 3 },
  { name: "Lighting & Electrical", slug: "tech-power", description: "Practical charging, visibility and phone solutions for modern vehicles.", imageUrl: media.light, isFeatured: true, sortOrder: 4 },
  { name: "Exterior & Touring", slug: "exterior-touring", description: "Flexible, road-ready storage and utility solutions for longer journeys.", imageUrl: media.utility, isFeatured: false, sortOrder: 5 },
  { name: "Phone & Navigation", slug: "phone-navigation", description: "Secure mounts and power accessories for safer everyday navigation.", imageUrl: media.mount, isFeatured: false, sortOrder: 6 },
  { name: "Workshop & Tools", slug: "workshop-tools", description: "Compact tools and practical garage essentials for quick checks and simple maintenance.", imageUrl: media.inflator, isFeatured: false, sortOrder: 7 },
  { name: "Seasonal Essentials", slug: "seasonal-essentials", description: "Weather-aware driving gear for colder mornings, warm journeys and changing conditions.", imageUrl: media.utility, isFeatured: false, sortOrder: 8 },
  { name: "Fluids & Maintenance", slug: "fluids-maintenance", description: "Engine oils, screenwash, coolant, bulbs and everyday upkeep essentials for a better prepared vehicle.", imageUrl: media.inflator, isFeatured: true, sortOrder: 9 },
  { name: "Performance & Handling", slug: "performance-handling", description: "Carefully selected road-focused upgrades for drivers who value a more responsive, composed drive.", imageUrl: media.utility, isFeatured: true, sortOrder: 10 },
  { name: "Braking & Service", slug: "braking-service", description: "Everyday service essentials, compatible replacement items and workshop-ready maintenance supplies.", imageUrl: media.inflator, isFeatured: false, sortOrder: 11 },
  { name: "Diagnostics & Garage", slug: "diagnostics-garage", description: "Useful scan tools, inspection equipment and practical garage organisation for informed vehicle care.", imageUrl: media.light, isFeatured: false, sortOrder: 12 },
  { name: "Audio & Dash Tech", slug: "audio-dash-tech", description: "Connected driving accessories, discreet recording solutions and practical infotainment upgrades.", imageUrl: media.mount, isFeatured: true, sortOrder: 13 },
  { name: "Wiper & Visibility", slug: "wiper-visibility", description: "Seasonal visibility essentials and universal-fit replacements for clearer, more prepared journeys.", imageUrl: media.light, isFeatured: false, sortOrder: 14 },
];

for (const category of categoryRows) await db.insert(categories).values(category).onConflictDoUpdate({ target: categories.slug, set: category });

const brandRows = [
  { name: "Northline", slug: "northline", description: "Practical vehicle essentials for everyday miles.", logoUrl: null },
  { name: "VelaWorks", slug: "velaworks", description: "Clean, dependable electrical and navigation accessories.", logoUrl: null },
  { name: "Sierra Form", slug: "sierra-form", description: "Car care tools designed for repeat use.", logoUrl: null },
  { name: "Atlas Supply", slug: "atlas-supply", description: "Storage and preparedness equipment for road trips and touring.", logoUrl: null },
  { name: "Roadwell", slug: "roadwell", description: "Compact workshop equipment for useful checks and simple roadside maintenance.", logoUrl: null },
  { name: "Fieldline", slug: "fieldline", description: "Travel and exterior equipment shaped around practical road use.", logoUrl: null },
  { name: "Kintra", slug: "kintra", description: "Seasonal comfort and visibility essentials for everyday driving.", logoUrl: null },
  { name: "Meridian Auto", slug: "meridian-auto", description: "Straightforward fluids and maintenance essentials for routine vehicle care.", logoUrl: null },
  { name: "Apexline", slug: "apexline", description: "Road-focused performance and handling accessories for considered everyday upgrades.", logoUrl: null },
  { name: "Torquefield", slug: "torquefield", description: "Dependable braking and service essentials for busy independent workshops.", logoUrl: null },
  { name: "DriveScope", slug: "drivescope", description: "Practical diagnostics and garage tools that make routine checks more approachable.", logoUrl: null },
  { name: "SignalRoute", slug: "signalroute", description: "Clean, connected dash technology for modern journeys and client vehicles.", logoUrl: null },
  { name: "Clearline", slug: "clearline", description: "Visibility-first wiper and weather-care essentials for changing road conditions.", logoUrl: null },
];

for (const brand of brandRows) await db.insert(brands).values(brand).onConflictDoUpdate({ target: brands.slug, set: brand });

const categoryLookup = new Map();
for (const item of categoryRows) {
  const row = await db.select({ id: categories.id }).from(categories).where(eq(categories.slug, item.slug)).limit(1);
  categoryLookup.set(item.slug, row[0].id);
}
const brandLookup = new Map();
for (const item of brandRows) {
  const row = await db.select({ id: brands.id }).from(brands).where(eq(brands.slug, item.slug)).limit(1);
  brandLookup.set(item.slug, row[0].id);
}

const productRows = [
  { name: "Orbit Air Digital Tyre Inflator", slug: "orbit-air-digital-tyre-inflator", sku: "ZM-ORB-100", shortDescription: "A compact 12V inflator for quick, clear tyre-pressure top-ups.", description: "Keep tyre checks simple at home, on a road trip or before a long commute. Orbit Air has a digital pressure readout, a flexible hose and a compact carry case.", specifications: { VehicleExamples: "Toyota Corolla, Ford Ranger, VW Golf, Mazda CX-5", Power: "12V vehicle socket", Display: "Digital pressure readout", Storage: "Compact zip case" }, price: "39.90", compareAtPrice: "49.90", stockQuantity: 46, imageUrl: media.inflator, categoryId: categoryLookup.get("roadside-utility"), brandId: brandLookup.get("northline"), isFeatured: true, isNew: true, isActive: true },
  { name: "Sierra All-Season Detail Kit", slug: "sierra-all-season-detail-kit", sku: "ZM-SIR-200", shortDescription: "A four-piece wash and interior-care set for regular use.", description: "A straightforward collection for paintwork, trims and cabin surfaces. The kit includes a cleaner, microfiber cloth, soft brush and finishing wax.", specifications: { VehicleExamples: "Universal fit for UK, US and Australian vehicles", Contents: "Four-piece care set", Surfaces: "Paint, plastic and interior trim", Cloth: "Dense microfiber" }, price: "32.00", compareAtPrice: "39.00", stockQuantity: 58, imageUrl: media.detailKit, categoryId: categoryLookup.get("car-care"), brandId: brandLookup.get("sierra-form"), isFeatured: true, isNew: false, isActive: true },
  { name: "Atlas Boot Organiser", slug: "atlas-boot-organiser", sku: "ZM-ATL-320", shortDescription: "Fold-flat boot storage for cables, groceries, recovery gear and travel items.", description: "A structured organiser with adjustable dividers and a non-slip base. Use it in a hatchback, SUV, ute or pickup to keep loose essentials in one place.", specifications: { VehicleExamples: "Ford Ranger, Toyota Hilux, Subaru Outback, VW Tiguan", Compartments: "Adjustable dividers", Base: "Non-slip", Format: "Fold-flat" }, price: "44.00", compareAtPrice: null, stockQuantity: 35, imageUrl: media.organizer, categoryId: categoryLookup.get("exterior-touring"), brandId: brandLookup.get("atlas-supply"), isFeatured: true, isNew: true, isActive: true },
  { name: "Vela Magnetic Phone Mount", slug: "vela-magnetic-phone-mount", sku: "ZM-VEL-410", shortDescription: "A compact vent mount that holds navigation securely and neatly.", description: "Vela keeps your phone visible without filling the windscreen. Its metal vent clip and rotating magnetic head suit everyday navigation in a wide range of vehicles.", specifications: { VehicleExamples: "Ford F-150, Honda Civic, BMW 3 Series, Toyota Yaris", Mount: "Magnetic vent clip", Rotation: "360-degree adjustment", Included: "Slim mounting ring" }, price: "19.00", compareAtPrice: "24.00", stockQuantity: 82, imageUrl: media.mount, categoryId: categoryLookup.get("phone-navigation"), brandId: brandLookup.get("velaworks"), isFeatured: true, isNew: false, isActive: true },
  { name: "Nova Emergency Beacon Light", slug: "nova-emergency-beacon-light", sku: "ZM-NOV-510", shortDescription: "A rechargeable roadside visibility light with a magnetic base.", description: "Store Nova in the boot or side compartment for unexpected stops. The weather-ready housing and amber beacon help make your vehicle more visible when needed.", specifications: { VehicleExamples: "Universal fit for sedans, SUVs, utes and pickups", Light: "Amber emergency beacon", Power: "Rechargeable", Base: "Magnetic" }, price: "27.00", compareAtPrice: null, stockQuantity: 64, imageUrl: media.light, categoryId: categoryLookup.get("roadside-utility"), brandId: brandLookup.get("atlas-supply"), isFeatured: false, isNew: true, isActive: true },
  { name: "Northline Vent & Trim Brush", slug: "northline-vent-trim-brush", sku: "ZM-NOR-620", shortDescription: "Soft detailing bristles for vents, seams and hard-to-reach cabin surfaces.", description: "A compact, washable brush for the small interior spaces that collect dust quickly. The textured handle is easy to grip while the bristles stay gentle on trim.", specifications: { VehicleExamples: "Universal cabin accessory", Bristles: "Soft synthetic", Grip: "Textured handle", Care: "Washable" }, price: "12.00", compareAtPrice: null, stockQuantity: 94, imageUrl: media.detailKit, categoryId: categoryLookup.get("car-care"), brandId: brandLookup.get("northline"), isFeatured: false, isNew: false, isActive: true },
  { name: "Vela RoadCharge 45W Adapter", slug: "vela-roadcharge-45w-adapter", sku: "ZM-VEL-710", shortDescription: "A dual-port 12V charger for phones, tablets and navigation devices.", description: "RoadCharge delivers practical fast charging without clutter. Two ports make it easy to keep a phone and passenger device powered on longer drives.", specifications: { VehicleExamples: "Toyota RAV4, Ford Focus, Hyundai i30, Mazda 3", Output: "45W dual-port", Ports: "USB-C and USB-A", Connection: "12V vehicle socket" }, price: "29.00", compareAtPrice: "34.00", stockQuantity: 73, imageUrl: media.mount, categoryId: categoryLookup.get("tech-power"), brandId: brandLookup.get("velaworks"), isFeatured: false, isNew: true, isActive: true },
  { name: "Atlas Seatback Travel Organiser", slug: "atlas-seatback-travel-organiser", sku: "ZM-ATL-820", shortDescription: "A slim seatback organiser for family trips, work travel and everyday storage.", description: "Keep cables, water bottles, travel documents and passenger essentials in easy reach. The adjustable straps suit most front seatbacks without a bulky profile.", specifications: { VehicleExamples: "Kia Sportage, Toyota Prado, Ford Explorer, Skoda Octavia", Pockets: "Six compartments", Material: "Wipe-clean fabric", Fit: "Adjustable seatback straps" }, price: "36.00", compareAtPrice: null, stockQuantity: 39, imageUrl: media.organizer, categoryId: categoryLookup.get("cabin-comfort"), brandId: brandLookup.get("atlas-supply"), isFeatured: true, isNew: false, isActive: true },
  { name: "Sierra Microfibre Drying Towel", slug: "sierra-microfibre-drying-towel", sku: "ZM-SIR-910", shortDescription: "A large, absorbent towel for quick wash-day drying without harsh friction.", description: "A practical finishing towel for weekly cleaning and seasonal detailing. Its dense weave absorbs water efficiently and is machine washable for repeat use.", specifications: { VehicleExamples: "Universal car-care accessory", Size: "Large drying format", Weave: "High-absorbency microfiber", Care: "Machine washable" }, price: "18.00", compareAtPrice: null, stockQuantity: 108, imageUrl: media.detailKit, categoryId: categoryLookup.get("car-care"), brandId: brandLookup.get("sierra-form"), isFeatured: false, isNew: true, isActive: true },
  { name: "Northline LED Inspection Light", slug: "northline-led-inspection-light", sku: "ZM-NOR-1020", shortDescription: "A rechargeable work light for boot checks, campsite setup and quick repairs.", description: "A compact inspection light with a sturdy magnetic base and simple USB charging. Keep one in the garage, boot or touring kit for useful light where you need it.", specifications: { VehicleExamples: "Universal for garage, touring and roadside use", Light: "LED work light", Mount: "Magnetic base", Charging: "USB rechargeable" }, price: "25.00", compareAtPrice: "30.00", stockQuantity: 52, imageUrl: media.light, categoryId: categoryLookup.get("tech-power"), brandId: brandLookup.get("northline"), isFeatured: true, isNew: true, isActive: true },
];

const expandedProductRows = [
  { name: "Sierra Ceramic Wash Concentrate", slug: "sierra-ceramic-wash-concentrate", sku: "ZM-SIR-1100", shortDescription: "A pH-neutral wash concentrate for regular exterior care.", description: "A measured wash concentrate that lifts road film while keeping routine cleaning straightforward.", specifications: { VehicleExamples: "Universal paintwork care", Format: "500ml concentrate", Use: "Bucket wash", Finish: "Gloss-supporting" }, price: "16.00", compareAtPrice: null, stockQuantity: 90, imageUrl: media.detailKit, categoryId: categoryLookup.get("car-care"), brandId: brandLookup.get("sierra-form"), isFeatured: false, isNew: true, isActive: true },
  { name: "Sierra Glass Clarity Kit", slug: "sierra-glass-clarity-kit", sku: "ZM-SIR-1110", shortDescription: "A streak-free glass-care set for windscreens, mirrors and interior glass.", description: "A simple two-piece visibility kit for clear glass before early starts and long routes.", specifications: { VehicleExamples: "Universal vehicle glass", Contents: "Cleaner and microfiber", Use: "Interior and exterior", Finish: "Low-streak" }, price: "14.00", compareAtPrice: null, stockQuantity: 84, imageUrl: media.detailKit, categoryId: categoryLookup.get("car-care"), brandId: brandLookup.get("sierra-form"), isFeatured: false, isNew: false, isActive: true },
  { name: "Sierra Wheel Detail Brush", slug: "sierra-wheel-detail-brush", sku: "ZM-SIR-1120", shortDescription: "A flexible wheel brush for regular cleaning around spokes and trims.", description: "Soft but durable bristles help reach common wheel and grille details without harsh scraping.", specifications: { VehicleExamples: "Universal wheel care", Bristles: "Flexible synthetic", Grip: "Non-slip handle", Care: "Rinse after use" }, price: "11.00", compareAtPrice: null, stockQuantity: 76, imageUrl: media.detailKit, categoryId: categoryLookup.get("car-care"), brandId: brandLookup.get("sierra-form"), isFeatured: false, isNew: false, isActive: true },
  { name: "Sierra Cabin Fabric Refresh", slug: "sierra-cabin-fabric-refresh", sku: "ZM-SIR-1130", shortDescription: "A gentle interior spray for fabric seats and boot linings.", description: "A compact refresh spray designed for everyday cabin fabric care between deeper cleans.", specifications: { VehicleExamples: "Fabric-seat vehicles", Format: "300ml spray", Surfaces: "Seats and boot lining", Use: "Spot refresh" }, price: "13.00", compareAtPrice: "16.00", stockQuantity: 71, imageUrl: media.detailKit, categoryId: categoryLookup.get("car-care"), brandId: brandLookup.get("sierra-form"), isFeatured: false, isNew: true, isActive: true },
  { name: "Sierra Paint Guard Detailer", slug: "sierra-paint-guard-detailer", sku: "ZM-SIR-1140", shortDescription: "A quick-detail spray for light dust and fingerprints between washes.", description: "Keep the finish looking cared for with a simple wipe-on detailer for routine use.", specifications: { VehicleExamples: "Universal painted panels", Format: "500ml spray", Use: "Between washes", Finish: "Gloss enhancer" }, price: "15.00", compareAtPrice: null, stockQuantity: 67, imageUrl: media.detailKit, categoryId: categoryLookup.get("car-care"), brandId: brandLookup.get("sierra-form"), isFeatured: false, isNew: false, isActive: true },
  { name: "Atlas Rear Seat Organiser", slug: "atlas-rear-seat-organiser", sku: "ZM-ATL-1150", shortDescription: "A clean-lined organiser for family travel, work bags and daily essentials.", description: "Multiple pockets keep small travel items accessible without taking over the cabin.", specifications: { VehicleExamples: "SUVs, sedans and hatchbacks", Pockets: "Seven compartments", Fit: "Adjustable straps", Care: "Wipe-clean" }, price: "31.00", compareAtPrice: null, stockQuantity: 48, imageUrl: media.organizer, categoryId: categoryLookup.get("cabin-comfort"), brandId: brandLookup.get("atlas-supply"), isFeatured: false, isNew: true, isActive: true },
  { name: "Atlas Compact Cabin Bin", slug: "atlas-compact-cabin-bin", sku: "ZM-ATL-1160", shortDescription: "A low-profile cabin bin for everyday wrappers and small waste.", description: "A discreet reusable bin that fits neatly where a full-size container would be impractical.", specifications: { VehicleExamples: "Universal cabin accessory", Format: "Compact hanging bin", Liner: "Removable", Mount: "Adjustable strap" }, price: "17.00", compareAtPrice: null, stockQuantity: 68, imageUrl: media.organizer, categoryId: categoryLookup.get("cabin-comfort"), brandId: brandLookup.get("atlas-supply"), isFeatured: false, isNew: false, isActive: true },
  { name: "Atlas Drive Support Cushion", slug: "atlas-drive-support-cushion", sku: "ZM-ATL-1170", shortDescription: "A shaped seat cushion for longer commutes and touring routes.", description: "A removable comfort layer designed to make longer periods behind the wheel feel more supported.", specifications: { VehicleExamples: "Universal front seats", Fill: "Support foam", Cover: "Breathable fabric", Fit: "Adjustable strap" }, price: "38.00", compareAtPrice: "45.00", stockQuantity: 34, imageUrl: media.organizer, categoryId: categoryLookup.get("cabin-comfort"), brandId: brandLookup.get("atlas-supply"), isFeatured: true, isNew: true, isActive: true },
  { name: "Atlas Journey Table Tray", slug: "atlas-journey-table-tray", sku: "ZM-ATL-1180", shortDescription: "A fold-flat travel tray for parked breaks and rear-seat passengers.", description: "A compact tray that creates a useful surface for snacks, tablets or work when parked.", specifications: { VehicleExamples: "Most front seatbacks", Format: "Fold-flat tray", Surface: "Wipe-clean", Fit: "Seatback mount" }, price: "22.00", compareAtPrice: null, stockQuantity: 53, imageUrl: media.organizer, categoryId: categoryLookup.get("cabin-comfort"), brandId: brandLookup.get("atlas-supply"), isFeatured: false, isNew: false, isActive: true },
  { name: "Atlas Windshield Sunshade Set", slug: "atlas-windshield-sunshade-set", sku: "ZM-ATL-1190", shortDescription: "A folding front-screen shade for warmer parked days.", description: "A simple reflective screen that folds away when not in use and helps reduce direct cabin heat.", specifications: { VehicleExamples: "Sedans, SUVs and hatchbacks", Format: "Folding screen", Finish: "Reflective layer", Storage: "Carry sleeve" }, price: "19.00", compareAtPrice: null, stockQuantity: 80, imageUrl: media.utility, categoryId: categoryLookup.get("cabin-comfort"), brandId: brandLookup.get("atlas-supply"), isFeatured: false, isNew: true, isActive: true },
  { name: "Northline Compact Jump Pack", slug: "northline-compact-jump-pack", sku: "ZM-NOR-1200", shortDescription: "A compact power pack for battery support and USB charging on the road.", description: "A travel-ready jump pack for keeping in the boot when longer routes call for useful backup.", specifications: { VehicleExamples: "Petrol cars and compact SUVs", Capacity: "8000mAh", Ports: "USB-C and USB-A", Storage: "Zip case" }, price: "79.00", compareAtPrice: "89.00", stockQuantity: 27, imageUrl: media.inflator, categoryId: categoryLookup.get("roadside-utility"), brandId: brandLookup.get("northline"), isFeatured: true, isNew: true, isActive: true },
  { name: "Northline Roadside Triangle Set", slug: "northline-roadside-triangle-set", sku: "ZM-NOR-1210", shortDescription: "A folding high-visibility triangle pair for roadside preparedness.", description: "A compact pair of folding warning triangles designed for a more visible roadside stop.", specifications: { VehicleExamples: "Universal roadside kit", Contents: "Two folding triangles", Storage: "Hard case", Finish: "Reflective panels" }, price: "24.00", compareAtPrice: null, stockQuantity: 61, imageUrl: media.light, categoryId: categoryLookup.get("roadside-utility"), brandId: brandLookup.get("northline"), isFeatured: false, isNew: false, isActive: true },
  { name: "Northline Recovery Strap", slug: "northline-recovery-strap", sku: "ZM-NOR-1220", shortDescription: "A compact recovery strap for prepared touring kits.", description: "A durable strap supplied in a tidy storage bag for off-road and touring equipment kits.", specifications: { VehicleExamples: "SUVs, utes and pickups", Length: "4 metres", Storage: "Carry bag", Use: "Recovery preparation" }, price: "29.00", compareAtPrice: null, stockQuantity: 41, imageUrl: media.utility, categoryId: categoryLookup.get("roadside-utility"), brandId: brandLookup.get("northline"), isFeatured: false, isNew: true, isActive: true },
  { name: "Northline Smart Tyre Gauge", slug: "northline-smart-tyre-gauge", sku: "ZM-NOR-1230", shortDescription: "A compact digital gauge for clear routine pressure checks.", description: "A pocket-sized digital gauge for quick tyre checks at home, at work or before touring.", specifications: { VehicleExamples: "Cars, SUVs and pickups", Display: "Digital readout", Range: "0–100 PSI", Storage: "Protective cap" }, price: "14.00", compareAtPrice: null, stockQuantity: 95, imageUrl: media.inflator, categoryId: categoryLookup.get("roadside-utility"), brandId: brandLookup.get("northline"), isFeatured: false, isNew: false, isActive: true },
  { name: "Northline Boot Flask Holder", slug: "northline-boot-flask-holder", sku: "ZM-NOR-1240", shortDescription: "A secure upright holder for bottles and travel flasks in the boot.", description: "Keep bottles stable during the drive with a small organiser insert that fits into touring setups.", specifications: { VehicleExamples: "Universal boot accessory", Fit: "Adjustable base", Use: "Bottles and flasks", Care: "Wipe-clean" }, price: "16.00", compareAtPrice: null, stockQuantity: 64, imageUrl: media.organizer, categoryId: categoryLookup.get("roadside-utility"), brandId: brandLookup.get("northline"), isFeatured: false, isNew: false, isActive: true },
  { name: "Vela Dual USB Socket", slug: "vela-dual-usb-socket", sku: "ZM-VEL-1250", shortDescription: "A compact 12V charger with dual USB outputs for daily devices.", description: "A practical dual-port charger for keeping navigation and passenger devices ready on longer days.", specifications: { VehicleExamples: "12V vehicle sockets", Output: "30W combined", Ports: "USB-C and USB-A", Indicator: "Soft LED" }, price: "18.00", compareAtPrice: "22.00", stockQuantity: 103, imageUrl: media.mount, categoryId: categoryLookup.get("tech-power"), brandId: brandLookup.get("velaworks"), isFeatured: false, isNew: false, isActive: true },
  { name: "Vela Wireless Charge Pad", slug: "vela-wireless-charge-pad", sku: "ZM-VEL-1260", shortDescription: "A low-profile charging pad designed for a tidy centre console.", description: "A compact charging surface that keeps an everyday phone accessible and ready while parked.", specifications: { VehicleExamples: "Qi-compatible devices", Output: "15W wireless", Surface: "Non-slip", Cable: "USB-C included" }, price: "27.00", compareAtPrice: null, stockQuantity: 51, imageUrl: media.mount, categoryId: categoryLookup.get("tech-power"), brandId: brandLookup.get("velaworks"), isFeatured: true, isNew: true, isActive: true },
  { name: "Vela Diagnostic Display Mount", slug: "vela-diagnostic-display-mount", sku: "ZM-VEL-1270", shortDescription: "A discreet mount for compatible compact driving displays.", description: "A simple adjustable mount that keeps a small dashboard display clear without blocking key controls.", specifications: { VehicleExamples: "Flat dashboard surfaces", Rotation: "360-degree adjustment", Mount: "Adhesive base", Finish: "Matte black" }, price: "21.00", compareAtPrice: null, stockQuantity: 47, imageUrl: media.mount, categoryId: categoryLookup.get("tech-power"), brandId: brandLookup.get("velaworks"), isFeatured: false, isNew: false, isActive: true },
  { name: "Vela LED Boot Strip", slug: "vela-led-boot-strip", sku: "ZM-VEL-1280", shortDescription: "A flexible LED strip for a brighter boot and touring setup.", description: "A practical rechargeable light strip for storage areas, camping setup and quick boot checks.", specifications: { VehicleExamples: "Boots and touring storage", Light: "Warm white LED", Charging: "USB-C", Mount: "Magnetic tabs" }, price: "23.00", compareAtPrice: null, stockQuantity: 58, imageUrl: media.light, categoryId: categoryLookup.get("tech-power"), brandId: brandLookup.get("velaworks"), isFeatured: false, isNew: true, isActive: true },
  { name: "Vela Battery Health Meter", slug: "vela-battery-health-meter", sku: "ZM-VEL-1290", shortDescription: "A small plug-in meter for a quick 12V battery status check.", description: "A simple dashboard-ready readout that helps make battery checks more visible before a trip.", specifications: { VehicleExamples: "12V passenger vehicles", Display: "Voltage readout", Connection: "12V socket", Use: "Quick check" }, price: "20.00", compareAtPrice: null, stockQuantity: 49, imageUrl: media.inflator, categoryId: categoryLookup.get("tech-power"), brandId: brandLookup.get("velaworks"), isFeatured: false, isNew: false, isActive: true },
  { name: "Fieldline Roof Travel Bag", slug: "fieldline-roof-travel-bag", sku: "ZM-FLD-1300", shortDescription: "A soft travel bag for organised weekend and touring storage.", description: "A structured travel bag with weather-aware fabric and tidy handles for a more prepared route.", specifications: { VehicleExamples: "SUVs and touring vehicles", Capacity: "45 litres", Material: "Water-resistant fabric", Storage: "Fold-flat" }, price: "69.00", compareAtPrice: "79.00", stockQuantity: 21, imageUrl: media.utility, categoryId: categoryLookup.get("exterior-touring"), brandId: brandLookup.get("fieldline"), isFeatured: true, isNew: true, isActive: true },
  { name: "Fieldline All-Weather Boot Mat", slug: "fieldline-all-weather-boot-mat", sku: "ZM-FLD-1310", shortDescription: "A universal cut-to-fit boot mat for wet boots, gear and groceries.", description: "A durable protective layer for keeping the load area easier to clean through changing seasons.", specifications: { VehicleExamples: "Hatchbacks, SUVs and estates", Material: "Textured rubber", Fit: "Trim-to-fit", Care: "Rinse-clean" }, price: "34.00", compareAtPrice: null, stockQuantity: 43, imageUrl: media.utility, categoryId: categoryLookup.get("exterior-touring"), brandId: brandLookup.get("fieldline"), isFeatured: false, isNew: false, isActive: true },
  { name: "Fieldline Door Edge Guard Set", slug: "fieldline-door-edge-guard-set", sku: "ZM-FLD-1320", shortDescription: "A flexible trim set for helping protect common door-edge contact points.", description: "A simple cut-to-length protective strip for everyday parking spaces and tighter garage access.", specifications: { VehicleExamples: "Universal door edges", Length: "5 metres", Fit: "Cut-to-length", Finish: "Low-profile black" }, price: "12.00", compareAtPrice: null, stockQuantity: 96, imageUrl: media.utility, categoryId: categoryLookup.get("exterior-touring"), brandId: brandLookup.get("fieldline"), isFeatured: false, isNew: false, isActive: true },
  { name: "Fieldline Roof Tie-Down Set", slug: "fieldline-roof-tie-down-set", sku: "ZM-FLD-1330", shortDescription: "A two-strap set for securing compatible touring loads.", description: "A practical strap set supplied with a storage pouch for compatible roof and cargo setups.", specifications: { VehicleExamples: "Compatible roof-rack systems", Contents: "Two straps", Length: "3 metres each", Storage: "Carry pouch" }, price: "26.00", compareAtPrice: null, stockQuantity: 39, imageUrl: media.utility, categoryId: categoryLookup.get("exterior-touring"), brandId: brandLookup.get("fieldline"), isFeatured: false, isNew: true, isActive: true },
  { name: "Fieldline Mud Guard Pair", slug: "fieldline-mud-guard-pair", sku: "ZM-FLD-1340", shortDescription: "A universal flexible guard pair for road spray and light debris.", description: "A practical pair of guards for drivers who want a more protected lower-body finish on everyday routes.", specifications: { VehicleExamples: "Cars and compact SUVs", Material: "Flexible rubber", Contents: "Pair", Finish: "Matte black" }, price: "28.00", compareAtPrice: null, stockQuantity: 46, imageUrl: media.utility, categoryId: categoryLookup.get("exterior-touring"), brandId: brandLookup.get("fieldline"), isFeatured: false, isNew: false, isActive: true },
  { name: "Vela Universal Dash Mount", slug: "vela-universal-dash-mount", sku: "ZM-VEL-1350", shortDescription: "An adjustable dashboard mount for phone-based navigation.", description: "A stable adjustable mount that keeps navigation in view while leaving the windscreen clear.", specifications: { VehicleExamples: "Most smartphones", Rotation: "360-degree", Mount: "Dashboard adhesive", Grip: "Adjustable arms" }, price: "24.00", compareAtPrice: null, stockQuantity: 88, imageUrl: media.mount, categoryId: categoryLookup.get("phone-navigation"), brandId: brandLookup.get("velaworks"), isFeatured: false, isNew: true, isActive: true },
  { name: "Vela Cable Management Clips", slug: "vela-cable-management-clips", sku: "ZM-VEL-1360", shortDescription: "A small clip set for tidier charging and navigation cables.", description: "A practical set of clips that reduces cable movement around the dashboard and console.", specifications: { VehicleExamples: "Universal cabin accessory", Contents: "Six clips", Mount: "Adhesive base", Finish: "Matte black" }, price: "8.00", compareAtPrice: null, stockQuantity: 130, imageUrl: media.mount, categoryId: categoryLookup.get("phone-navigation"), brandId: brandLookup.get("velaworks"), isFeatured: false, isNew: false, isActive: true },
  { name: "Vela Driving Screen Shade", slug: "vela-driving-screen-shade", sku: "ZM-VEL-1370", shortDescription: "A small visor that helps reduce direct glare on compatible navigation screens.", description: "A compact shade designed to improve screen visibility in brighter conditions without a bulky installation.", specifications: { VehicleExamples: "Compatible 7–9 inch screens", Fit: "Clip-on", Finish: "Low-reflection", Material: "ABS polymer" }, price: "15.00", compareAtPrice: null, stockQuantity: 62, imageUrl: media.mount, categoryId: categoryLookup.get("phone-navigation"), brandId: brandLookup.get("velaworks"), isFeatured: false, isNew: false, isActive: true },
  { name: "Vela Magnetic Vent Mount Pro", slug: "vela-magnetic-vent-mount-pro", sku: "ZM-VEL-1380", shortDescription: "A stronger magnetic vent mount for compact phone navigation.", description: "A revised vent mount with a metal clip and a firm magnetic surface for everyday use.", specifications: { VehicleExamples: "Most horizontal vents", Mount: "Magnetic vent clip", Rotation: "360-degree", Included: "Slim ring" }, price: "22.00", compareAtPrice: null, stockQuantity: 75, imageUrl: media.mount, categoryId: categoryLookup.get("phone-navigation"), brandId: brandLookup.get("velaworks"), isFeatured: true, isNew: false, isActive: true },
  { name: "Vela Navigation Charge Cable", slug: "vela-navigation-charge-cable", sku: "ZM-VEL-1390", shortDescription: "A low-profile USB-C cable for tidy dashboard charging.", description: "A durable cable in a useful length for connecting a navigation phone without excess slack.", specifications: { VehicleExamples: "USB-C compatible devices", Length: "1.2 metres", Connector: "USB-C", Finish: "Braided cable" }, price: "10.00", compareAtPrice: null, stockQuantity: 122, imageUrl: media.mount, categoryId: categoryLookup.get("phone-navigation"), brandId: brandLookup.get("velaworks"), isFeatured: false, isNew: true, isActive: true },
  { name: "Roadwell Socket Tool Roll", slug: "roadwell-socket-tool-roll", sku: "ZM-RDW-1400", shortDescription: "A tidy compact tool roll for a prepared garage or touring kit.", description: "A useful fabric roll with common small sockets and a space-saving storage layout.", specifications: { VehicleExamples: "Garage and touring use", Contents: "Metric sockets", Storage: "Tool roll", Handle: "Carry loop" }, price: "42.00", compareAtPrice: "49.00", stockQuantity: 37, imageUrl: media.inflator, categoryId: categoryLookup.get("workshop-tools"), brandId: brandLookup.get("roadwell"), isFeatured: true, isNew: true, isActive: true },
  { name: "Roadwell Trim Tool Set", slug: "roadwell-trim-tool-set", sku: "ZM-RDW-1410", shortDescription: "A non-marking tool set for compatible trim and interior adjustments.", description: "A compact set of polymer tools suited to careful interior and panel work.", specifications: { VehicleExamples: "Universal trim work", Contents: "Five tools", Material: "Non-marking polymer", Storage: "Slim pouch" }, price: "18.00", compareAtPrice: null, stockQuantity: 65, imageUrl: media.inflator, categoryId: categoryLookup.get("workshop-tools"), brandId: brandLookup.get("roadwell"), isFeatured: false, isNew: false, isActive: true },
  { name: "Roadwell Folding Work Mat", slug: "roadwell-folding-work-mat", sku: "ZM-RDW-1420", shortDescription: "A foldable kneeling mat for quick garage and roadside checks.", description: "A lightweight foam mat that folds down small between use and protects knees on hard ground.", specifications: { VehicleExamples: "Garage and roadside use", Material: "Closed-cell foam", Format: "Foldable", Care: "Wipe-clean" }, price: "20.00", compareAtPrice: null, stockQuantity: 56, imageUrl: media.inflator, categoryId: categoryLookup.get("workshop-tools"), brandId: brandLookup.get("roadwell"), isFeatured: false, isNew: false, isActive: true },
  { name: "Roadwell Compact Torque Wrench", slug: "roadwell-compact-torque-wrench", sku: "ZM-RDW-1430", shortDescription: "A compact adjustable wrench for compatible maintenance tasks.", description: "A well-balanced hand tool designed for a tidy home-garage toolkit.", specifications: { VehicleExamples: "Garage maintenance use", Drive: "3/8 inch", Range: "20–110Nm", Storage: "Protective case" }, price: "54.00", compareAtPrice: null, stockQuantity: 24, imageUrl: media.inflator, categoryId: categoryLookup.get("workshop-tools"), brandId: brandLookup.get("roadwell"), isFeatured: true, isNew: false, isActive: true },
  { name: "Roadwell Micro Repair Kit", slug: "roadwell-micro-repair-kit", sku: "ZM-RDW-1440", shortDescription: "A compact essentials kit for small fixes in the garage or on a trip.", description: "A portable kit with common small fasteners and hand tools for practical quick fixes.", specifications: { VehicleExamples: "Universal emergency kit", Contents: "Small tools and fasteners", Storage: "Hard case", Use: "Minor repairs" }, price: "33.00", compareAtPrice: null, stockQuantity: 44, imageUrl: media.inflator, categoryId: categoryLookup.get("workshop-tools"), brandId: brandLookup.get("roadwell"), isFeatured: false, isNew: true, isActive: true },
  { name: "Kintra Winter Visibility Pack", slug: "kintra-winter-visibility-pack", sku: "ZM-KIN-1450", shortDescription: "A compact seasonal kit for frosty mornings and low-visibility conditions.", description: "A useful seasonal bundle with a scraper, microfiber cloth and visibility-ready essentials.", specifications: { VehicleExamples: "UK and European winter driving", Contents: "Three-piece kit", Storage: "Compact pouch", Use: "Cold mornings" }, price: "19.00", compareAtPrice: null, stockQuantity: 82, imageUrl: media.utility, categoryId: categoryLookup.get("seasonal-essentials"), brandId: brandLookup.get("kintra"), isFeatured: true, isNew: true, isActive: true },
  { name: "Kintra Windshield Cover", slug: "kintra-windshield-cover", sku: "ZM-KIN-1460", shortDescription: "A folding windscreen cover for colder parked mornings.", description: "A simple protective cover that helps make morning starts a little more straightforward.", specifications: { VehicleExamples: "Sedans, SUVs and hatchbacks", Mount: "Door-flap tabs", Storage: "Carry sleeve", Use: "Frost and sun" }, price: "17.00", compareAtPrice: null, stockQuantity: 74, imageUrl: media.utility, categoryId: categoryLookup.get("seasonal-essentials"), brandId: brandLookup.get("kintra"), isFeatured: false, isNew: false, isActive: true },
  { name: "Kintra Vent Sunshade", slug: "kintra-vent-sunshade", sku: "ZM-KIN-1470", shortDescription: "A lightweight sunshade for hotter parking and road-trip stops.", description: "A simple folding shade designed to help keep direct cabin heat more manageable.", specifications: { VehicleExamples: "Universal windscreen fit", Format: "Accordion fold", Finish: "Reflective", Storage: "Slim strap" }, price: "15.00", compareAtPrice: null, stockQuantity: 91, imageUrl: media.utility, categoryId: categoryLookup.get("seasonal-essentials"), brandId: brandLookup.get("kintra"), isFeatured: false, isNew: true, isActive: true },
  { name: "Kintra Boot Weather Kit", slug: "kintra-boot-weather-kit", sku: "ZM-KIN-1480", shortDescription: "A compact carry kit for wet-weather drives and muddy stops.", description: "A simple boot kit with a reusable towel, protective gloves and a washable storage bag.", specifications: { VehicleExamples: "Universal boot kit", Contents: "Three practical pieces", Bag: "Water-resistant", Use: "Wet-weather travel" }, price: "26.00", compareAtPrice: null, stockQuantity: 55, imageUrl: media.utility, categoryId: categoryLookup.get("seasonal-essentials"), brandId: brandLookup.get("kintra"), isFeatured: false, isNew: false, isActive: true },
  { name: "Kintra Anti-Fog Cloth Set", slug: "kintra-anti-fog-cloth-set", sku: "ZM-KIN-1490", shortDescription: "A reusable cloth pair for routine interior-glass care.", description: "A compact cloth set designed for keeping interior glass clearer during damp or cold conditions.", specifications: { VehicleExamples: "Universal interior glass", Contents: "Two cloths", Care: "Machine washable", Use: "Interior visibility" }, price: "9.00", compareAtPrice: null, stockQuantity: 118, imageUrl: media.detailKit, categoryId: categoryLookup.get("seasonal-essentials"), brandId: brandLookup.get("kintra"), isFeatured: false, isNew: true, isActive: true },
];

const essentialProductRows = [
  { name: "Meridian 5W-30 Fully Synthetic Engine Oil", slug: "meridian-5w-30-fully-synthetic-engine-oil", sku: "ZM-MER-1500", shortDescription: "A 5L fully synthetic engine oil for vehicles that specify 5W-30 grade.", description: "A practical 5L maintenance essential for compatible petrol and diesel vehicles. Always confirm the required viscosity and specification in the vehicle handbook before use.", specifications: { VehicleExamples: "Compatible vehicles that specify 5W-30", Volume: "5 litres", Grade: "5W-30", Use: "Check vehicle handbook" }, price: "38.00", compareAtPrice: "43.00", stockQuantity: 62, imageUrl: media.inflator, categoryId: categoryLookup.get("fluids-maintenance"), brandId: brandLookup.get("meridian-auto"), isFeatured: true, isNew: true, isActive: true },
  { name: "Meridian 0W-20 Engine Oil", slug: "meridian-0w-20-engine-oil", sku: "ZM-MER-1510", shortDescription: "A 5L low-viscosity engine oil for compatible modern petrol and hybrid vehicles.", description: "A low-viscosity oil intended only for engines that specify 0W-20. Consult the handbook or a qualified technician before selecting a grade.", specifications: { VehicleExamples: "Compatible petrol and hybrid engines", Volume: "5 litres", Grade: "0W-20", Use: "Handbook-confirmed fit" }, price: "42.00", compareAtPrice: null, stockQuantity: 48, imageUrl: media.inflator, categoryId: categoryLookup.get("fluids-maintenance"), brandId: brandLookup.get("meridian-auto"), isFeatured: false, isNew: true, isActive: true },
  { name: "Meridian 10W-40 Engine Oil", slug: "meridian-10w-40-engine-oil", sku: "ZM-MER-1520", shortDescription: "A 5L engine oil option for vehicles that specify 10W-40 grade.", description: "A straightforward engine oil for compatible vehicles where 10W-40 is the specified grade. Confirm your engine requirements before use.", specifications: { VehicleExamples: "Compatible engines that specify 10W-40", Volume: "5 litres", Grade: "10W-40", Use: "Check vehicle handbook" }, price: "34.00", compareAtPrice: null, stockQuantity: 55, imageUrl: media.inflator, categoryId: categoryLookup.get("fluids-maintenance"), brandId: brandLookup.get("meridian-auto"), isFeatured: false, isNew: false, isActive: true },
  { name: "Meridian 5W-30 Top-Up Oil", slug: "meridian-5w-30-top-up-oil", sku: "ZM-MER-1530", shortDescription: "A 1L top-up bottle for compatible engines using 5W-30 oil.", description: "A compact top-up format for vehicles confirmed to require the matching 5W-30 oil grade.", specifications: { VehicleExamples: "Compatible 5W-30 engines", Volume: "1 litre", Grade: "5W-30", Format: "Top-up bottle" }, price: "11.00", compareAtPrice: null, stockQuantity: 93, imageUrl: media.inflator, categoryId: categoryLookup.get("fluids-maintenance"), brandId: brandLookup.get("meridian-auto"), isFeatured: false, isNew: false, isActive: true },
  { name: "Meridian Long-Life Coolant", slug: "meridian-long-life-coolant", sku: "ZM-MER-1540", shortDescription: "A 1L coolant concentrate for compatible cooling systems.", description: "A practical cooling-system maintenance product. Match coolant type and dilution requirements to the vehicle handbook before use.", specifications: { VehicleExamples: "Compatible cooling systems", Volume: "1 litre", Format: "Concentrate", Use: "Handbook-confirmed type" }, price: "12.00", compareAtPrice: null, stockQuantity: 76, imageUrl: media.inflator, categoryId: categoryLookup.get("fluids-maintenance"), brandId: brandLookup.get("meridian-auto"), isFeatured: false, isNew: true, isActive: true },
  { name: "Meridian All-Season Screenwash", slug: "meridian-all-season-screenwash", sku: "ZM-MER-1550", shortDescription: "A 5L screenwash concentrate for clearer everyday driving visibility.", description: "A useful screenwash concentrate for routine top-ups and seasonal visibility care. Dilute as directed on the product label.", specifications: { VehicleExamples: "Universal windscreen washer systems", Volume: "5 litres", Format: "Concentrate", Use: "Dilute as labelled" }, price: "10.00", compareAtPrice: null, stockQuantity: 106, imageUrl: media.inflator, categoryId: categoryLookup.get("fluids-maintenance"), brandId: brandLookup.get("meridian-auto"), isFeatured: true, isNew: true, isActive: true },
  { name: "Meridian Petrol Fuel-System Cleaner", slug: "meridian-petrol-fuel-system-cleaner", sku: "ZM-MER-1560", shortDescription: "A measured petrol fuel-system additive for compatible gasoline engines.", description: "A maintenance additive for petrol engines when used according to its label. It is not fuel and should be selected only for compatible gasoline vehicles.", specifications: { VehicleExamples: "Compatible petrol or gasoline engines", Volume: "300ml", Format: "Fuel-system additive", Use: "Follow label directions" }, price: "9.00", compareAtPrice: null, stockQuantity: 84, imageUrl: media.inflator, categoryId: categoryLookup.get("fluids-maintenance"), brandId: brandLookup.get("meridian-auto"), isFeatured: false, isNew: true, isActive: true },
  { name: "Meridian Diesel Injector Cleaner", slug: "meridian-diesel-injector-cleaner", sku: "ZM-MER-1570", shortDescription: "A diesel-system additive for compatible diesel vehicles.", description: "A carefully measured maintenance additive for diesel fuel systems. Check compatibility and use it only as directed on the label.", specifications: { VehicleExamples: "Compatible diesel engines", Volume: "300ml", Format: "Fuel-system additive", Use: "Follow label directions" }, price: "10.00", compareAtPrice: null, stockQuantity: 71, imageUrl: media.inflator, categoryId: categoryLookup.get("fluids-maintenance"), brandId: brandLookup.get("meridian-auto"), isFeatured: false, isNew: false, isActive: true },
  { name: "Meridian DOT 4 Brake Fluid", slug: "meridian-dot-4-brake-fluid", sku: "ZM-MER-1580", shortDescription: "A 500ml DOT 4 brake fluid for compatible systems and qualified maintenance.", description: "A fluid maintenance essential for systems that specify DOT 4. Brake servicing is safety-critical; confirm compatibility and seek qualified help when needed.", specifications: { VehicleExamples: "Vehicles specifying DOT 4", Volume: "500ml", Grade: "DOT 4", Use: "Qualified maintenance advised" }, price: "8.00", compareAtPrice: null, stockQuantity: 64, imageUrl: media.inflator, categoryId: categoryLookup.get("fluids-maintenance"), brandId: brandLookup.get("meridian-auto"), isFeatured: false, isNew: false, isActive: true },
  { name: "Meridian AdBlue Top-Up", slug: "meridian-adblue-top-up", sku: "ZM-MER-1590", shortDescription: "A 5L top-up for compatible diesel emissions systems.", description: "A sealed AdBlue top-up format for diesel vehicles equipped with a compatible emissions system. Confirm your vehicle requirements before purchase.", specifications: { VehicleExamples: "Compatible diesel emissions systems", Volume: "5 litres", Format: "Sealed top-up", Use: "Check vehicle handbook" }, price: "15.00", compareAtPrice: null, stockQuantity: 58, imageUrl: media.inflator, categoryId: categoryLookup.get("fluids-maintenance"), brandId: brandLookup.get("meridian-auto"), isFeatured: false, isNew: true, isActive: true },
  { name: "Northline Battery Terminal Care Kit", slug: "northline-battery-terminal-care-kit", sku: "ZM-NOR-1600", shortDescription: "A compact brush and protector kit for clean, cared-for battery terminals.", description: "A simple maintenance kit for accessible battery-terminal cleaning and protection. Use only with the vehicle switched off and follow safe battery-handling guidance.", specifications: { VehicleExamples: "Accessible 12V battery terminals", Contents: "Brush and protective treatment", Use: "Battery care", Safety: "Vehicle switched off" }, price: "14.00", compareAtPrice: null, stockQuantity: 67, imageUrl: media.inflator, categoryId: categoryLookup.get("fluids-maintenance"), brandId: brandLookup.get("northline"), isFeatured: false, isNew: true, isActive: true },
  { name: "Northline Compact Battery Conditioner", slug: "northline-compact-battery-conditioner", sku: "ZM-NOR-1610", shortDescription: "A compact 12V conditioner for compatible vehicle batteries.", description: "A practical battery-care accessory for compatible 12V vehicle batteries, with clear status lights and a compact lead set.", specifications: { VehicleExamples: "Compatible 12V vehicle batteries", Power: "Mains powered", Status: "LED indicators", Use: "Battery maintenance" }, price: "46.00", compareAtPrice: "54.00", stockQuantity: 33, imageUrl: media.inflator, categoryId: categoryLookup.get("tech-power"), brandId: brandLookup.get("northline"), isFeatured: true, isNew: true, isActive: true },
  { name: "Nova H7 Halogen Bulb Twin Pack", slug: "nova-h7-halogen-bulb-twin-pack", sku: "ZM-NOV-1620", shortDescription: "A twin-pack replacement bulb option for headlamps that specify H7 fitment.", description: "A practical replacement pair for vehicles that use H7 halogen bulbs. Confirm the correct bulb type and local road-use requirements before purchase.", specifications: { VehicleExamples: "Vehicles that specify H7 halogen bulbs", Contents: "Twin pack", BulbType: "H7 halogen", Fit: "Confirm handbook" }, price: "18.00", compareAtPrice: null, stockQuantity: 86, imageUrl: media.light, categoryId: categoryLookup.get("tech-power"), brandId: brandLookup.get("kintra"), isFeatured: false, isNew: true, isActive: true },
  { name: "Nova W5W Interior Bulb Pair", slug: "nova-w5w-interior-bulb-pair", sku: "ZM-NOV-1630", shortDescription: "A compact replacement bulb pair for compatible W5W interior fittings.", description: "A useful spare bulb pair for compatible cabin, boot or number-plate fittings. Match the fitting to your vehicle before purchase.", specifications: { VehicleExamples: "Compatible W5W fittings", Contents: "Two bulbs", BulbType: "W5W", Fit: "Confirm handbook" }, price: "7.00", compareAtPrice: null, stockQuantity: 112, imageUrl: media.light, categoryId: categoryLookup.get("tech-power"), brandId: brandLookup.get("kintra"), isFeatured: false, isNew: false, isActive: true },
  { name: "Vela MagDrive Wireless Car Charger", slug: "vela-magdrive-wireless-car-charger", sku: "ZM-VEL-1640", shortDescription: "A magnetic wireless charger for compatible phones and a tidy dashboard setup.", description: "A practical car charger with a secure magnetic hold for compatible devices. Confirm your phone and case support before use.", specifications: { VehicleExamples: "Compatible magnetic-charge phones", Power: "15W wireless charging", Mount: "Vent clip", Cable: "USB-C included" }, price: "37.00", compareAtPrice: "43.00", stockQuantity: 54, imageUrl: media.mount, categoryId: categoryLookup.get("phone-navigation"), brandId: brandLookup.get("velaworks"), isFeatured: true, isNew: true, isActive: true },
  { name: "Vela Dual-Port Travel Charger", slug: "vela-dual-port-travel-charger", sku: "ZM-VEL-1650", shortDescription: "A compact dual-port vehicle charger for phones, tablets and travel devices.", description: "A clean 12V charging option for keeping a driver's phone and passenger device powered on everyday journeys.", specifications: { VehicleExamples: "12V vehicle sockets", Output: "36W dual-port", Ports: "USB-C and USB-A", Use: "Phone and travel devices" }, price: "24.00", compareAtPrice: null, stockQuantity: 89, imageUrl: media.mount, categoryId: categoryLookup.get("phone-navigation"), brandId: brandLookup.get("velaworks"), isFeatured: false, isNew: true, isActive: true },
  { name: "Vela Cable Management Clip Set", slug: "vela-cable-management-clip-set", sku: "ZM-VEL-1660", shortDescription: "A six-piece cable clip set for tidier in-car phone charging.", description: "A small practical set for guiding compatible charging cables along a dashboard or console without loose loops.", specifications: { VehicleExamples: "Universal interior use", Contents: "Six adhesive clips", Use: "Cable organisation", Finish: "Low-profile black" }, price: "8.00", compareAtPrice: null, stockQuantity: 130, imageUrl: media.mount, categoryId: categoryLookup.get("phone-navigation"), brandId: brandLookup.get("velaworks"), isFeatured: false, isNew: false, isActive: true },
];

const clientDemoProductRows = [
  { name: "Apexline Street Response Air Filter", slug: "apexline-street-response-air-filter", sku: "ZM-APX-1700", shortDescription: "A reusable panel filter for compatible road vehicles and routine service checks.", description: "A practical replacement-style filter for clients who want a clean, well-supported intake service item. Always confirm the correct fitment before purchase.", specifications: { VehicleExamples: "Compatible UK, US and Australian passenger vehicles", Format: "Panel-style filter", Care: "Serviceable element", Fitment: "Confirm vehicle application" }, price: "42.00", compareAtPrice: "49.00", stockQuantity: 38, imageUrl: media.utility, categoryId: categoryLookup.get("performance-handling"), brandId: brandLookup.get("apexline"), isFeatured: true, isNew: true, isActive: true },
  { name: "Apexline Road Balance Steering Wheel Cover", slug: "apexline-road-balance-steering-wheel-cover", sku: "ZM-APX-1710", shortDescription: "A stitched, non-slip steering wheel cover for a more secure everyday grip.", description: "A smart cabin upgrade with a clean perforated finish and a flexible universal-fit design for many compatible steering wheels.", specifications: { VehicleExamples: "Most passenger-vehicle steering wheels", Material: "Perforated synthetic leather", Grip: "Non-slip lining", Fitment: "Universal-size range" }, price: "24.00", compareAtPrice: null, stockQuantity: 76, imageUrl: media.utility, categoryId: categoryLookup.get("performance-handling"), brandId: brandLookup.get("apexline"), isFeatured: false, isNew: true, isActive: true },
  { name: "Apexline Tyre Valve Cap Set", slug: "apexline-tyre-valve-cap-set", sku: "ZM-APX-1720", shortDescription: "A four-piece weather-resistant valve-cap set for a tidy finishing detail.", description: "A simple small-format accessory for routine wheel care and a more considered presentation on customer vehicles.", specifications: { VehicleExamples: "Standard passenger-car tyre valves", Contents: "Four caps", Finish: "Matte graphite", Weather: "Weather-resistant" }, price: "9.00", compareAtPrice: null, stockQuantity: 140, imageUrl: media.utility, categoryId: categoryLookup.get("performance-handling"), brandId: brandLookup.get("apexline"), isFeatured: false, isNew: false, isActive: true },
  { name: "Torquefield Premium Cabin Filter", slug: "torquefield-premium-cabin-filter", sku: "ZM-TRQ-1730", shortDescription: "A replacement-style cabin filter with a fine-particle layer for compatible vehicles.", description: "A clear, workshop-ready service item for supporting fresher cabin airflow. Fitment should always be confirmed against the vehicle application.", specifications: { VehicleExamples: "Compatible passenger vehicles", Layer: "Fine-particle filter media", Service: "Routine replacement", Fitment: "Vehicle-specific confirmation" }, price: "21.00", compareAtPrice: null, stockQuantity: 66, imageUrl: media.inflator, categoryId: categoryLookup.get("braking-service"), brandId: brandLookup.get("torquefield"), isFeatured: true, isNew: true, isActive: true },
  { name: "Torquefield Brake Care Starter Pack", slug: "torquefield-brake-care-starter-pack", sku: "ZM-TRQ-1740", shortDescription: "A practical workshop pack for externally accessible brake-component cleaning tasks.", description: "A garage-friendly care pack intended for qualified service work. Brake systems are safety-critical; use qualified technicians and confirm product suitability.", specifications: { VehicleExamples: "Workshop use", Contents: "Cleaner and application accessories", Use: "Qualified maintenance", Safety: "Follow product directions" }, price: "28.00", compareAtPrice: "33.00", stockQuantity: 42, imageUrl: media.inflator, categoryId: categoryLookup.get("braking-service"), brandId: brandLookup.get("torquefield"), isFeatured: false, isNew: true, isActive: true },
  { name: "Torquefield Service Funnel Set", slug: "torquefield-service-funnel-set", sku: "ZM-TRQ-1750", shortDescription: "A three-piece flexible funnel set for cleaner workshop fluid handling.", description: "A simple bench-side service accessory for shops that value cleaner, more organised routine maintenance.", specifications: { VehicleExamples: "Workshop and garage use", Contents: "Three flexible funnels", Material: "Oil-resistant polymer", Storage: "Nested set" }, price: "16.00", compareAtPrice: null, stockQuantity: 85, imageUrl: media.inflator, categoryId: categoryLookup.get("braking-service"), brandId: brandLookup.get("torquefield"), isFeatured: false, isNew: false, isActive: true },
  { name: "DriveScope Pocket OBD Reader", slug: "drivescope-pocket-obd-reader", sku: "ZM-DRV-1760", shortDescription: "A compact Bluetooth diagnostic reader for compatible OBD-II vehicles.", description: "A client-friendly scan accessory designed to support basic code reading through a compatible mobile app. It does not replace qualified diagnosis.", specifications: { VehicleExamples: "Compatible OBD-II vehicles", Connection: "Bluetooth", Use: "Basic code reading", Note: "Not a substitute for professional diagnosis" }, price: "34.00", compareAtPrice: "39.00", stockQuantity: 54, imageUrl: media.light, categoryId: categoryLookup.get("diagnostics-garage"), brandId: brandLookup.get("drivescope"), isFeatured: true, isNew: true, isActive: true },
  { name: "DriveScope Magnetic Inspection Mirror", slug: "drivescope-magnetic-inspection-mirror", sku: "ZM-DRV-1770", shortDescription: "A telescopic inspection mirror with a magnetic tip for workshop visibility.", description: "A compact garage tool for seeing into difficult areas during non-critical visual checks and retrieving small ferrous items.", specifications: { VehicleExamples: "Garage and workshop use", Reach: "Telescopic handle", Head: "Adjustable mirror", Tip: "Magnetic retrieval" }, price: "18.00", compareAtPrice: null, stockQuantity: 59, imageUrl: media.light, categoryId: categoryLookup.get("diagnostics-garage"), brandId: brandLookup.get("drivescope"), isFeatured: false, isNew: false, isActive: true },
  { name: "DriveScope Workshop Service Mat", slug: "drivescope-workshop-service-mat", sku: "ZM-DRV-1780", shortDescription: "A wipe-clean padded kneeling mat for more comfortable workshop preparation.", description: "A durable, easy-clean support mat designed for busy shop environments and everyday garage tasks.", specifications: { VehicleExamples: "Workshop and garage use", Material: "Closed-cell foam", Surface: "Wipe-clean", Format: "Portable mat" }, price: "20.00", compareAtPrice: null, stockQuantity: 48, imageUrl: media.light, categoryId: categoryLookup.get("diagnostics-garage"), brandId: brandLookup.get("drivescope"), isFeatured: false, isNew: true, isActive: true },
  { name: "SignalRoute Roadview Dash Camera", slug: "signalroute-roadview-dash-camera", sku: "ZM-SIG-1790", shortDescription: "A compact front-facing recording camera for supported road-trip documentation.", description: "A discreet dash camera with a tidy suction mount and a simple app-ready workflow. Local recording and privacy requirements should be checked before use.", specifications: { VehicleExamples: "Most passenger vehicle windscreens", Video: "Full HD recording", Connection: "Mobile app compatible", Note: "Observe local privacy and road laws" }, price: "84.00", compareAtPrice: "99.00", stockQuantity: 31, imageUrl: media.mount, categoryId: categoryLookup.get("audio-dash-tech"), brandId: brandLookup.get("signalroute"), isFeatured: true, isNew: true, isActive: true },
  { name: "SignalRoute Wireless CarPlay Adapter", slug: "signalroute-wireless-carplay-adapter", sku: "ZM-SIG-1800", shortDescription: "A plug-in adapter for compatible wired smartphone-projection systems.", description: "A small console accessory for eligible vehicles where a supported wired smartphone-projection system is already fitted.", specifications: { VehicleExamples: "Vehicles with compatible wired projection", Connection: "USB plug-in", Format: "Compact adapter", Fitment: "Check head-unit compatibility" }, price: "58.00", compareAtPrice: null, stockQuantity: 44, imageUrl: media.mount, categoryId: categoryLookup.get("audio-dash-tech"), brandId: brandLookup.get("signalroute"), isFeatured: false, isNew: true, isActive: true },
  { name: "SignalRoute Console Cable Kit", slug: "signalroute-console-cable-kit", sku: "ZM-SIG-1810", shortDescription: "A durable USB-C cable set for a neater charging and infotainment setup.", description: "A three-cable kit with compact right-angle ends designed to help clients keep a centre console more organised.", specifications: { VehicleExamples: "USB-C compatible devices", Contents: "Three cable lengths", Connector: "Right-angle USB-C", Storage: "Velcro organiser" }, price: "15.00", compareAtPrice: null, stockQuantity: 97, imageUrl: media.mount, categoryId: categoryLookup.get("audio-dash-tech"), brandId: brandLookup.get("signalroute"), isFeatured: false, isNew: false, isActive: true },
  { name: "Clearline FlexFit Wiper Blade Pair", slug: "clearline-flexfit-wiper-blade-pair", sku: "ZM-CLR-1820", shortDescription: "A low-profile replacement wiper pair with multiple compatible adapter fittings.", description: "A practical visibility replacement for eligible vehicles. Use the included fitment guide and confirm the correct blade lengths before purchase.", specifications: { VehicleExamples: "Compatible passenger vehicles", Contents: "Front blade pair", Style: "Low-profile beam", Fitment: "Confirm length and connector" }, price: "26.00", compareAtPrice: "30.00", stockQuantity: 72, imageUrl: media.light, categoryId: categoryLookup.get("wiper-visibility"), brandId: brandLookup.get("clearline"), isFeatured: true, isNew: true, isActive: true },
  { name: "Clearline Rain Vision Treatment", slug: "clearline-rain-vision-treatment", sku: "ZM-CLR-1830", shortDescription: "A windscreen treatment for clearer wet-weather water shedding when used as directed.", description: "A small-format visibility-care product for external glass. Follow the label directions and prepare the surface before application.", specifications: { VehicleExamples: "External vehicle glass", Format: "100ml treatment", Use: "Wet-weather glass care", Application: "Follow label directions" }, price: "13.00", compareAtPrice: null, stockQuantity: 103, imageUrl: media.light, categoryId: categoryLookup.get("wiper-visibility"), brandId: brandLookup.get("clearline"), isFeatured: false, isNew: false, isActive: true },
  { name: "Clearline Screenwash Concentrate", slug: "clearline-screenwash-concentrate", sku: "ZM-CLR-1840", shortDescription: "A concentrated screenwash top-up for seasonal visibility care.", description: "A straightforward maintenance fluid for use in compatible washer systems. Dilute and use according to the label and weather conditions.", specifications: { VehicleExamples: "Compatible washer reservoirs", Format: "1L concentrate", Use: "Seasonal dilution", Note: "Follow label directions" }, price: "9.00", compareAtPrice: null, stockQuantity: 118, imageUrl: media.light, categoryId: categoryLookup.get("wiper-visibility"), brandId: brandLookup.get("clearline"), isFeatured: false, isNew: true, isActive: true },
];

const motorOilProductRows = [
  { name: "Meridian 5W-40 Fully Synthetic Engine Oil", slug: "meridian-5w-40-fully-synthetic-engine-oil", sku: "ZM-MER-1840", shortDescription: "A 5L fully synthetic motor oil for petrol and diesel vehicles that specify 5W-40.", description: "A workshop-ready 5L engine oil for compatible vehicles that require a 5W-40 grade. Confirm the required viscosity and manufacturer specification in the vehicle handbook before use.", specifications: { VehicleExamples: "Compatible petrol and diesel vehicles that specify 5W-40", Volume: "5 litres", Grade: "5W-40", Quality: "Fully synthetic", FitCheck: "Match your vehicle handbook" }, price: "40.00", compareAtPrice: "46.00", stockQuantity: 57, imageUrl: media.inflator, categoryId: categoryLookup.get("fluids-maintenance"), brandId: brandLookup.get("meridian-auto"), isFeatured: true, isNew: true, isActive: true },
  { name: "Meridian 0W-30 Low-SAPS Engine Oil", slug: "meridian-0w-30-low-saps-engine-oil", sku: "ZM-MER-1850", shortDescription: "A 5L low-SAPS motor oil for compatible modern engines that specify 0W-30.", description: "A low-viscosity 0W-30 option for compatible modern engines. Always match the listed grade and manufacturer approval with your vehicle handbook or qualified technician before ordering.", specifications: { VehicleExamples: "Compatible engines that specify 0W-30", Volume: "5 litres", Grade: "0W-30", Quality: "Low-SAPS synthetic", FitCheck: "Match your vehicle handbook" }, price: "45.00", compareAtPrice: null, stockQuantity: 41, imageUrl: media.inflator, categoryId: categoryLookup.get("fluids-maintenance"), brandId: brandLookup.get("meridian-auto"), isFeatured: false, isNew: true, isActive: true },
  { name: "Meridian 5W-30 Workshop Pack", slug: "meridian-5w-30-workshop-pack", sku: "ZM-MER-1860", shortDescription: "A 20L workshop pack for service work on compatible vehicles that specify 5W-30.", description: "A larger-format 5W-30 fully synthetic motor oil option for service planning and workshop use. Confirm the grade, approval and required volume for every vehicle before use.", specifications: { VehicleExamples: "Compatible vehicles that specify 5W-30", Volume: "20 litres", Grade: "5W-30", Quality: "Fully synthetic", FitCheck: "Confirm vehicle requirement" }, price: "142.00", compareAtPrice: "158.00", stockQuantity: 18, imageUrl: media.inflator, categoryId: categoryLookup.get("fluids-maintenance"), brandId: brandLookup.get("meridian-auto"), isFeatured: false, isNew: true, isActive: true },
];

const diversifiedMedia = product => {
  if (product.name.startsWith("Meridian") && product.name.includes("Oil")) return "/manus-storage/zalim-meridian-motor-oil_d2ae9ba4.png";
  if (product.name.startsWith("Sierra")) return "/manus-storage/zalim-detailing-care-accessories_d8371c0f.jpg";
  if (product.name.startsWith("Roadwell")) return "/manus-storage/zalim-workshop-tools-accessories_82a7c8af.jpg";
  if (product.name.startsWith("Kintra")) return "/manus-storage/zalim-all-weather-accessories_22fe2de0.jpg";
  if (product.name.startsWith("Fieldline")) return "/manus-storage/zalim-premium-road-trip-accessories_f7116c14.jpg";
  if (product.name.startsWith("Atlas")) return "/manus-storage/zalim-cargo-organisation-accessories_08c75b43.jpg";
  if (product.name.startsWith("Vela")) return "/manus-storage/zalim-digital-driving-accessories_4b185c06.jpg";
  if (product.name.startsWith("Nova")) return "/manus-storage/zalim-lighting-visibility-accessories_28545c6b.jpg";
  if (product.name.startsWith("Meridian")) return "/manus-storage/zalim-workshop-tools-accessories_82a7c8af.jpg";
  if (product.name.startsWith("Orbit") || product.name.includes("Jump") || product.name.includes("Recovery") || product.name.includes("Tyre")) return "/manus-storage/zalim-roadside-recovery-accessories_15200369.jpg";
  if (product.name.startsWith("Northline")) return "/manus-storage/zalim-comfort-utility-accessories_3ed5fad3.jpg";
  if (product.name.startsWith("Apexline")) return "/manus-storage/zalim-premium-road-trip-accessories_f7116c14.jpg";
  if (product.name.startsWith("Torquefield")) return "/manus-storage/zalim-workshop-tools-accessories_82a7c8af.jpg";
  if (product.name.startsWith("DriveScope")) return "/manus-storage/zalim-workshop-tools-accessories_82a7c8af.jpg";
  if (product.name.startsWith("SignalRoute")) return "/manus-storage/zalim-digital-driving-accessories_4b185c06.jpg";
  if (product.name.startsWith("Clearline")) return "/manus-storage/zalim-lighting-visibility-accessories_28545c6b.jpg";
  return product.imageUrl;
};

for (const product of [...productRows, ...expandedProductRows, ...essentialProductRows, ...clientDemoProductRows, ...motorOilProductRows]) {
  const seededProduct = { ...product, imageUrl: diversifiedMedia(product) };
  await db.insert(products).values(seededProduct).onConflictDoUpdate({ target: products.slug, set: seededProduct });
}

console.log(`Seeded ${categoryRows.length} categories, ${brandRows.length} brands, and ${productRows.length + expandedProductRows.length + essentialProductRows.length + clientDemoProductRows.length + motorOilProductRows.length} products.`);
await pool.end();
