import { drizzle } from "drizzle-orm/mysql2";
import { eq } from "drizzle-orm";
import { brands, categories, products } from "../drizzle/schema.ts";

if (!process.env.DATABASE_URL) throw new Error("DATABASE_URL is required to seed the catalog.");

const db = drizzle(process.env.DATABASE_URL);
const media = {
  detailing: "/manus-storage/category-detailing_2f0366b5.jpg",
  interior: "/manus-storage/category-interior_d5e055da.jpg",
  utility: "/manus-storage/category-utility_fa340543.jpg",
  inflator: "/manus-storage/product-orbit-inflator_5d9564fd.jpg",
  detailKit: "/manus-storage/product-sierra-detail-kit_30c89008.jpg",
  organizer: "/manus-storage/product-atlas-organizer_955f56bc.jpg",
  mount: "/manus-storage/product-velar-mount_85a6698c.jpg",
  light: "/manus-storage/product-nova-light_24e6c57b.jpg",
};

const categoryRows = [
  { name: "Car Care", slug: "car-care", description: "Washing, detailing and seasonal protection for everyday cars and weekend projects.", imageUrl: media.detailing, isFeatured: true, sortOrder: 1 },
  { name: "Interior & Comfort", slug: "cabin-comfort", description: "Useful cabin storage, cleaning and travel upgrades for every drive.", imageUrl: media.interior, isFeatured: true, sortOrder: 2 },
  { name: "Safety & Utility", slug: "roadside-utility", description: "Roadside, boot and touring essentials for real-world preparedness.", imageUrl: media.utility, isFeatured: true, sortOrder: 3 },
  { name: "Lighting & Electrical", slug: "tech-power", description: "Practical charging, visibility and phone solutions for modern vehicles.", imageUrl: media.light, isFeatured: true, sortOrder: 4 },
  { name: "Exterior & Touring", slug: "exterior-touring", description: "Flexible, road-ready storage and utility solutions for longer journeys.", imageUrl: media.utility, isFeatured: false, sortOrder: 5 },
  { name: "Phone & Navigation", slug: "phone-navigation", description: "Secure mounts and power accessories for safer everyday navigation.", imageUrl: media.mount, isFeatured: false, sortOrder: 6 },
  { name: "Workshop & Tools", slug: "workshop-tools", description: "Compact tools and practical garage essentials for quick checks and simple maintenance.", imageUrl: media.inflator, isFeatured: false, sortOrder: 7 },
  { name: "Seasonal Essentials", slug: "seasonal-essentials", description: "Weather-aware driving gear for colder mornings, warm journeys and changing conditions.", imageUrl: media.utility, isFeatured: false, sortOrder: 8 },
];

for (const category of categoryRows) await db.insert(categories).values(category).onDuplicateKeyUpdate({ set: category });

const brandRows = [
  { name: "Northline", slug: "northline", description: "Practical vehicle essentials for everyday miles.", logoUrl: null },
  { name: "VelaWorks", slug: "velaworks", description: "Clean, dependable electrical and navigation accessories.", logoUrl: null },
  { name: "Sierra Form", slug: "sierra-form", description: "Car care tools designed for repeat use.", logoUrl: null },
  { name: "Atlas Supply", slug: "atlas-supply", description: "Storage and preparedness equipment for road trips and touring.", logoUrl: null },
  { name: "Roadwell", slug: "roadwell", description: "Compact workshop equipment for useful checks and simple roadside maintenance.", logoUrl: null },
  { name: "Fieldline", slug: "fieldline", description: "Travel and exterior equipment shaped around practical road use.", logoUrl: null },
  { name: "Kintra", slug: "kintra", description: "Seasonal comfort and visibility essentials for everyday driving.", logoUrl: null },
];

for (const brand of brandRows) await db.insert(brands).values(brand).onDuplicateKeyUpdate({ set: brand });

const categoryLookup = new Map();
for (const item of categoryRows) {
  const row = await db.select({ id: categories.id }).from(categories).where(eq(categories.slug, item.slug)).limit(1);
  categoryLookup.set(item.slug, row[0].id);
}
const brandLookup = new Map();
for (const item of brandRows) {
  const row = await db.select({ id: brands.id }).from(brands).where(eq(brands.slug, item.slug)).limit(1);
  brandLookup.set(item.slug, row[0].id);
}

const productRows = [
  { name: "Orbit Air Digital Tyre Inflator", slug: "orbit-air-digital-tyre-inflator", sku: "ZM-ORB-100", shortDescription: "A compact 12V inflator for quick, clear tyre-pressure top-ups.", description: "Keep tyre checks simple at home, on a road trip or before a long commute. Orbit Air has a digital pressure readout, a flexible hose and a compact carry case.", specifications: { VehicleExamples: "Toyota Corolla, Ford Ranger, VW Golf, Mazda CX-5", Power: "12V vehicle socket", Display: "Digital pressure readout", Storage: "Compact zip case" }, price: "39.90", compareAtPrice: "49.90", stockQuantity: 46, imageUrl: media.inflator, categoryId: categoryLookup.get("roadside-utility"), brandId: brandLookup.get("northline"), isFeatured: true, isNew: true, isActive: true },
  { name: "Sierra All-Season Detail Kit", slug: "sierra-all-season-detail-kit", sku: "ZM-SIR-200", shortDescription: "A four-piece wash and interior-care set for regular use.", description: "A straightforward collection for paintwork, trims and cabin surfaces. The kit includes a cleaner, microfiber cloth, soft brush and finishing wax.", specifications: { VehicleExamples: "Universal fit for UK, US and Australian vehicles", Contents: "Four-piece care set", Surfaces: "Paint, plastic and interior trim", Cloth: "Dense microfiber" }, price: "32.00", compareAtPrice: "39.00", stockQuantity: 58, imageUrl: media.detailKit, categoryId: categoryLookup.get("car-care"), brandId: brandLookup.get("sierra-form"), isFeatured: true, isNew: false, isActive: true },
  { name: "Atlas Boot Organiser", slug: "atlas-boot-organiser", sku: "ZM-ATL-320", shortDescription: "Fold-flat boot storage for cables, groceries, recovery gear and travel items.", description: "A structured organiser with adjustable dividers and a non-slip base. Use it in a hatchback, SUV, ute or pickup to keep loose essentials in one place.", specifications: { VehicleExamples: "Ford Ranger, Toyota Hilux, Subaru Outback, VW Tiguan", Compartments: "Adjustable dividers", Base: "Non-slip", Format: "Fold-flat" }, price: "44.00", compareAtPrice: null, stockQuantity: 35, imageUrl: media.organizer, categoryId: categoryLookup.get("exterior-touring"), brandId: brandLookup.get("atlas-supply"), isFeatured: true, isNew: true, isActive: true },
  { name: "Vela Magnetic Phone Mount", slug: "vela-magnetic-phone-mount", sku: "ZM-VEL-410", shortDescription: "A compact vent mount that holds navigation securely and neatly.", description: "Vela keeps your phone visible without filling the windscreen. Its metal vent clip and rotating magnetic head suit everyday navigation in a wide range of vehicles.", specifications: { VehicleExamples: "Ford F-150, Honda Civic, BMW 3 Series, Toyota Yaris", Mount: "Magnetic vent clip", Rotation: "360-degree adjustment", Included: "Slim mounting ring" }, price: "19.00", compareAtPrice: "24.00", stockQuantity: 82, imageUrl: media.mount, categoryId: categoryLookup.get("phone-navigation"), brandId: brandLookup.get("velaworks"), isFeatured: true, isNew: false, isActive: true },
  { name: "Nova Emergency Beacon Light", slug: "nova-emergency-beacon-light", sku: "ZM-NOV-510", shortDescription: "A rechargeable roadside visibility light with a magnetic base.", description: "Store Nova in the boot or side compartment for unexpected stops. The weather-ready housing and amber beacon help make your vehicle more visible when needed.", specifications: { VehicleExamples: "Universal fit for sedans, SUVs, utes and pickups", Light: "Amber emergency beacon", Power: "Rechargeable", Base: "Magnetic" }, price: "27.00", compareAtPrice: null, stockQuantity: 64, imageUrl: media.light, categoryId: categoryLookup.get("roadside-utility"), brandId: brandLookup.get("atlas-supply"), isFeatured: false, isNew: true, isActive: true },
  { name: "Northline Vent & Trim Brush", slug: "northline-vent-trim-brush", sku: "ZM-NOR-620", shortDescription: "Soft detailing bristles for vents, seams and hard-to-reach cabin surfaces.", description: "A compact, washable brush for the small interior spaces that collect dust quickly. The textured handle is easy to grip while the bristles stay gentle on trim.", specifications: { VehicleExamples: "Universal cabin accessory", Bristles: "Soft synthetic", Grip: "Textured handle", Care: "Washable" }, price: "12.00", compareAtPrice: null, stockQuantity: 94, imageUrl: media.detailKit, categoryId: categoryLookup.get("car-care"), brandId: brandLookup.get("northline"), isFeatured: false, isNew: false, isActive: true },
  { name: "Vela RoadCharge 45W Adapter", slug: "vela-roadcharge-45w-adapter", sku: "ZM-VEL-710", shortDescription: "A dual-port 12V charger for phones, tablets and navigation devices.", description: "RoadCharge delivers practical fast charging without clutter. Two ports make it easy to keep a phone and passenger device powered on longer drives.", specifications: { VehicleExamples: "Toyota RAV4, Ford Focus, Hyundai i30, Mazda 3", Output: "45W dual-port", Ports: "USB-C and USB-A", Connection: "12V vehicle socket" }, price: "29.00", compareAtPrice: "34.00", stockQuantity: 73, imageUrl: media.mount, categoryId: categoryLookup.get("tech-power"), brandId: brandLookup.get("velaworks"), isFeatured: false, isNew: true, isActive: true },
  { name: "Atlas Seatback Travel Organiser", slug: "atlas-seatback-travel-organiser", sku: "ZM-ATL-820", shortDescription: "A slim seatback organiser for family trips, work travel and everyday storage.", description: "Keep cables, water bottles, travel documents and passenger essentials in easy reach. The adjustable straps suit most front seatbacks without a bulky profile.", specifications: { VehicleExamples: "Kia Sportage, Toyota Prado, Ford Explorer, Skoda Octavia", Pockets: "Six compartments", Material: "Wipe-clean fabric", Fit: "Adjustable seatback straps" }, price: "36.00", compareAtPrice: null, stockQuantity: 39, imageUrl: media.organizer, categoryId: categoryLookup.get("cabin-comfort"), brandId: brandLookup.get("atlas-supply"), isFeatured: true, isNew: false, isActive: true },
  { name: "Sierra Microfibre Drying Towel", slug: "sierra-microfibre-drying-towel", sku: "ZM-SIR-910", shortDescription: "A large, absorbent towel for quick wash-day drying without harsh friction.", description: "A practical finishing towel for weekly cleaning and seasonal detailing. Its dense weave absorbs water efficiently and is machine washable for repeat use.", specifications: { VehicleExamples: "Universal car-care accessory", Size: "Large drying format", Weave: "High-absorbency microfiber", Care: "Machine washable" }, price: "18.00", compareAtPrice: null, stockQuantity: 108, imageUrl: media.detailKit, categoryId: categoryLookup.get("car-care"), brandId: brandLookup.get("sierra-form"), isFeatured: false, isNew: true, isActive: true },
  { name: "Northline LED Inspection Light", slug: "northline-led-inspection-light", sku: "ZM-NOR-1020", shortDescription: "A rechargeable work light for boot checks, campsite setup and quick repairs.", description: "A compact inspection light with a sturdy magnetic base and simple USB charging. Keep one in the garage, boot or touring kit for useful light where you need it.", specifications: { VehicleExamples: "Universal for garage, touring and roadside use", Light: "LED work light", Mount: "Magnetic base", Charging: "USB rechargeable" }, price: "25.00", compareAtPrice: "30.00", stockQuantity: 52, imageUrl: media.light, categoryId: categoryLookup.get("tech-power"), brandId: brandLookup.get("northline"), isFeatured: true, isNew: true, isActive: true },
];

const expandedProductRows = [
  { name: "Sierra Ceramic Wash Concentrate", slug: "sierra-ceramic-wash-concentrate", sku: "ZM-SIR-1100", shortDescription: "A pH-neutral wash concentrate for regular exterior care.", description: "A measured wash concentrate that lifts road film while keeping routine cleaning straightforward.", specifications: { VehicleExamples: "Universal paintwork care", Format: "500ml concentrate", Use: "Bucket wash", Finish: "Gloss-supporting" }, price: "16.00", compareAtPrice: null, stockQuantity: 90, imageUrl: media.detailKit, categoryId: categoryLookup.get("car-care"), brandId: brandLookup.get("sierra-form"), isFeatured: false, isNew: true, isActive: true },
  { name: "Sierra Glass Clarity Kit", slug: "sierra-glass-clarity-kit", sku: "ZM-SIR-1110", shortDescription: "A streak-free glass-care set for windscreens, mirrors and interior glass.", description: "A simple two-piece visibility kit for clear glass before early starts and long routes.", specifications: { VehicleExamples: "Universal vehicle glass", Contents: "Cleaner and microfiber", Use: "Interior and exterior", Finish: "Low-streak" }, price: "14.00", compareAtPrice: null, stockQuantity: 84, imageUrl: media.detailKit, categoryId: categoryLookup.get("car-care"), brandId: brandLookup.get("sierra-form"), isFeatured: false, isNew: false, isActive: true },
  { name: "Sierra Wheel Detail Brush", slug: "sierra-wheel-detail-brush", sku: "ZM-SIR-1120", shortDescription: "A flexible wheel brush for regular cleaning around spokes and trims.", description: "Soft but durable bristles help reach common wheel and grille details without harsh scraping.", specifications: { VehicleExamples: "Universal wheel care", Bristles: "Flexible synthetic", Grip: "Non-slip handle", Care: "Rinse after use" }, price: "11.00", compareAtPrice: null, stockQuantity: 76, imageUrl: media.detailKit, categoryId: categoryLookup.get("car-care"), brandId: brandLookup.get("sierra-form"), isFeatured: false, isNew: false, isActive: true },
  { name: "Sierra Cabin Fabric Refresh", slug: "sierra-cabin-fabric-refresh", sku: "ZM-SIR-1130", shortDescription: "A gentle interior spray for fabric seats and boot linings.", description: "A compact refresh spray designed for everyday cabin fabric care between deeper cleans.", specifications: { VehicleExamples: "Fabric-seat vehicles", Format: "300ml spray", Surfaces: "Seats and boot lining", Use: "Spot refresh" }, price: "13.00", compareAtPrice: "16.00", stockQuantity: 71, imageUrl: media.detailKit, categoryId: categoryLookup.get("car-care"), brandId: brandLookup.get("sierra-form"), isFeatured: false, isNew: true, isActive: true },
  { name: "Sierra Paint Guard Detailer", slug: "sierra-paint-guard-detailer", sku: "ZM-SIR-1140", shortDescription: "A quick-detail spray for light dust and fingerprints between washes.", description: "Keep the finish looking cared for with a simple wipe-on detailer for routine use.", specifications: { VehicleExamples: "Universal painted panels", Format: "500ml spray", Use: "Between washes", Finish: "Gloss enhancer" }, price: "15.00", compareAtPrice: null, stockQuantity: 67, imageUrl: media.detailKit, categoryId: categoryLookup.get("car-care"), brandId: brandLookup.get("sierra-form"), isFeatured: false, isNew: false, isActive: true },
  { name: "Atlas Rear Seat Organiser", slug: "atlas-rear-seat-organiser", sku: "ZM-ATL-1150", shortDescription: "A clean-lined organiser for family travel, work bags and daily essentials.", description: "Multiple pockets keep small travel items accessible without taking over the cabin.", specifications: { VehicleExamples: "SUVs, sedans and hatchbacks", Pockets: "Seven compartments", Fit: "Adjustable straps", Care: "Wipe-clean" }, price: "31.00", compareAtPrice: null, stockQuantity: 48, imageUrl: media.organizer, categoryId: categoryLookup.get("cabin-comfort"), brandId: brandLookup.get("atlas-supply"), isFeatured: false, isNew: true, isActive: true },
  { name: "Atlas Compact Cabin Bin", slug: "atlas-compact-cabin-bin", sku: "ZM-ATL-1160", shortDescription: "A low-profile cabin bin for everyday wrappers and small waste.", description: "A discreet reusable bin that fits neatly where a full-size container would be impractical.", specifications: { VehicleExamples: "Universal cabin accessory", Format: "Compact hanging bin", Liner: "Removable", Mount: "Adjustable strap" }, price: "17.00", compareAtPrice: null, stockQuantity: 68, imageUrl: media.organizer, categoryId: categoryLookup.get("cabin-comfort"), brandId: brandLookup.get("atlas-supply"), isFeatured: false, isNew: false, isActive: true },
  { name: "Atlas Drive Support Cushion", slug: "atlas-drive-support-cushion", sku: "ZM-ATL-1170", shortDescription: "A shaped seat cushion for longer commutes and touring routes.", description: "A removable comfort layer designed to make longer periods behind the wheel feel more supported.", specifications: { VehicleExamples: "Universal front seats", Fill: "Support foam", Cover: "Breathable fabric", Fit: "Adjustable strap" }, price: "38.00", compareAtPrice: "45.00", stockQuantity: 34, imageUrl: media.organizer, categoryId: categoryLookup.get("cabin-comfort"), brandId: brandLookup.get("atlas-supply"), isFeatured: true, isNew: true, isActive: true },
  { name: "Atlas Journey Table Tray", slug: "atlas-journey-table-tray", sku: "ZM-ATL-1180", shortDescription: "A fold-flat travel tray for parked breaks and rear-seat passengers.", description: "A compact tray that creates a useful surface for snacks, tablets or work when parked.", specifications: { VehicleExamples: "Most front seatbacks", Format: "Fold-flat tray", Surface: "Wipe-clean", Fit: "Seatback mount" }, price: "22.00", compareAtPrice: null, stockQuantity: 53, imageUrl: media.organizer, categoryId: categoryLookup.get("cabin-comfort"), brandId: brandLookup.get("atlas-supply"), isFeatured: false, isNew: false, isActive: true },
  { name: "Atlas Windshield Sunshade Set", slug: "atlas-windshield-sunshade-set", sku: "ZM-ATL-1190", shortDescription: "A folding front-screen shade for warmer parked days.", description: "A simple reflective screen that folds away when not in use and helps reduce direct cabin heat.", specifications: { VehicleExamples: "Sedans, SUVs and hatchbacks", Format: "Folding screen", Finish: "Reflective layer", Storage: "Carry sleeve" }, price: "19.00", compareAtPrice: null, stockQuantity: 80, imageUrl: media.utility, categoryId: categoryLookup.get("cabin-comfort"), brandId: brandLookup.get("atlas-supply"), isFeatured: false, isNew: true, isActive: true },
  { name: "Northline Compact Jump Pack", slug: "northline-compact-jump-pack", sku: "ZM-NOR-1200", shortDescription: "A compact power pack for battery support and USB charging on the road.", description: "A travel-ready jump pack for keeping in the boot when longer routes call for useful backup.", specifications: { VehicleExamples: "Petrol cars and compact SUVs", Capacity: "8000mAh", Ports: "USB-C and USB-A", Storage: "Zip case" }, price: "79.00", compareAtPrice: "89.00", stockQuantity: 27, imageUrl: media.inflator, categoryId: categoryLookup.get("roadside-utility"), brandId: brandLookup.get("northline"), isFeatured: true, isNew: true, isActive: true },
  { name: "Northline Roadside Triangle Set", slug: "northline-roadside-triangle-set", sku: "ZM-NOR-1210", shortDescription: "A folding high-visibility triangle pair for roadside preparedness.", description: "A compact pair of folding warning triangles designed for a more visible roadside stop.", specifications: { VehicleExamples: "Universal roadside kit", Contents: "Two folding triangles", Storage: "Hard case", Finish: "Reflective panels" }, price: "24.00", compareAtPrice: null, stockQuantity: 61, imageUrl: media.light, categoryId: categoryLookup.get("roadside-utility"), brandId: brandLookup.get("northline"), isFeatured: false, isNew: false, isActive: true },
  { name: "Northline Recovery Strap", slug: "northline-recovery-strap", sku: "ZM-NOR-1220", shortDescription: "A compact recovery strap for prepared touring kits.", description: "A durable strap supplied in a tidy storage bag for off-road and touring equipment kits.", specifications: { VehicleExamples: "SUVs, utes and pickups", Length: "4 metres", Storage: "Carry bag", Use: "Recovery preparation" }, price: "29.00", compareAtPrice: null, stockQuantity: 41, imageUrl: media.utility, categoryId: categoryLookup.get("roadside-utility"), brandId: brandLookup.get("northline"), isFeatured: false, isNew: true, isActive: true },
  { name: "Northline Smart Tyre Gauge", slug: "northline-smart-tyre-gauge", sku: "ZM-NOR-1230", shortDescription: "A compact digital gauge for clear routine pressure checks.", description: "A pocket-sized digital gauge for quick tyre checks at home, at work or before touring.", specifications: { VehicleExamples: "Cars, SUVs and pickups", Display: "Digital readout", Range: "0–100 PSI", Storage: "Protective cap" }, price: "14.00", compareAtPrice: null, stockQuantity: 95, imageUrl: media.inflator, categoryId: categoryLookup.get("roadside-utility"), brandId: brandLookup.get("northline"), isFeatured: false, isNew: false, isActive: true },
  { name: "Northline Boot Flask Holder", slug: "northline-boot-flask-holder", sku: "ZM-NOR-1240", shortDescription: "A secure upright holder for bottles and travel flasks in the boot.", description: "Keep bottles stable during the drive with a small organiser insert that fits into touring setups.", specifications: { VehicleExamples: "Universal boot accessory", Fit: "Adjustable base", Use: "Bottles and flasks", Care: "Wipe-clean" }, price: "16.00", compareAtPrice: null, stockQuantity: 64, imageUrl: media.organizer, categoryId: categoryLookup.get("roadside-utility"), brandId: brandLookup.get("northline"), isFeatured: false, isNew: false, isActive: true },
  { name: "Vela Dual USB Socket", slug: "vela-dual-usb-socket", sku: "ZM-VEL-1250", shortDescription: "A compact 12V charger with dual USB outputs for daily devices.", description: "A practical dual-port charger for keeping navigation and passenger devices ready on longer days.", specifications: { VehicleExamples: "12V vehicle sockets", Output: "30W combined", Ports: "USB-C and USB-A", Indicator: "Soft LED" }, price: "18.00", compareAtPrice: "22.00", stockQuantity: 103, imageUrl: media.mount, categoryId: categoryLookup.get("tech-power"), brandId: brandLookup.get("velaworks"), isFeatured: false, isNew: false, isActive: true },
  { name: "Vela Wireless Charge Pad", slug: "vela-wireless-charge-pad", sku: "ZM-VEL-1260", shortDescription: "A low-profile charging pad designed for a tidy centre console.", description: "A compact charging surface that keeps an everyday phone accessible and ready while parked.", specifications: { VehicleExamples: "Qi-compatible devices", Output: "15W wireless", Surface: "Non-slip", Cable: "USB-C included" }, price: "27.00", compareAtPrice: null, stockQuantity: 51, imageUrl: media.mount, categoryId: categoryLookup.get("tech-power"), brandId: brandLookup.get("velaworks"), isFeatured: true, isNew: true, isActive: true },
  { name: "Vela Diagnostic Display Mount", slug: "vela-diagnostic-display-mount", sku: "ZM-VEL-1270", shortDescription: "A discreet mount for compatible compact driving displays.", description: "A simple adjustable mount that keeps a small dashboard display clear without blocking key controls.", specifications: { VehicleExamples: "Flat dashboard surfaces", Rotation: "360-degree adjustment", Mount: "Adhesive base", Finish: "Matte black" }, price: "21.00", compareAtPrice: null, stockQuantity: 47, imageUrl: media.mount, categoryId: categoryLookup.get("tech-power"), brandId: brandLookup.get("velaworks"), isFeatured: false, isNew: false, isActive: true },
  { name: "Vela LED Boot Strip", slug: "vela-led-boot-strip", sku: "ZM-VEL-1280", shortDescription: "A flexible LED strip for a brighter boot and touring setup.", description: "A practical rechargeable light strip for storage areas, camping setup and quick boot checks.", specifications: { VehicleExamples: "Boots and touring storage", Light: "Warm white LED", Charging: "USB-C", Mount: "Magnetic tabs" }, price: "23.00", compareAtPrice: null, stockQuantity: 58, imageUrl: media.light, categoryId: categoryLookup.get("tech-power"), brandId: brandLookup.get("velaworks"), isFeatured: false, isNew: true, isActive: true },
  { name: "Vela Battery Health Meter", slug: "vela-battery-health-meter", sku: "ZM-VEL-1290", shortDescription: "A small plug-in meter for a quick 12V battery status check.", description: "A simple dashboard-ready readout that helps make battery checks more visible before a trip.", specifications: { VehicleExamples: "12V passenger vehicles", Display: "Voltage readout", Connection: "12V socket", Use: "Quick check" }, price: "20.00", compareAtPrice: null, stockQuantity: 49, imageUrl: media.inflator, categoryId: categoryLookup.get("tech-power"), brandId: brandLookup.get("velaworks"), isFeatured: false, isNew: false, isActive: true },
  { name: "Fieldline Roof Travel Bag", slug: "fieldline-roof-travel-bag", sku: "ZM-FLD-1300", shortDescription: "A soft travel bag for organised weekend and touring storage.", description: "A structured travel bag with weather-aware fabric and tidy handles for a more prepared route.", specifications: { VehicleExamples: "SUVs and touring vehicles", Capacity: "45 litres", Material: "Water-resistant fabric", Storage: "Fold-flat" }, price: "69.00", compareAtPrice: "79.00", stockQuantity: 21, imageUrl: media.utility, categoryId: categoryLookup.get("exterior-touring"), brandId: brandLookup.get("fieldline"), isFeatured: true, isNew: true, isActive: true },
  { name: "Fieldline All-Weather Boot Mat", slug: "fieldline-all-weather-boot-mat", sku: "ZM-FLD-1310", shortDescription: "A universal cut-to-fit boot mat for wet boots, gear and groceries.", description: "A durable protective layer for keeping the load area easier to clean through changing seasons.", specifications: { VehicleExamples: "Hatchbacks, SUVs and estates", Material: "Textured rubber", Fit: "Trim-to-fit", Care: "Rinse-clean" }, price: "34.00", compareAtPrice: null, stockQuantity: 43, imageUrl: media.utility, categoryId: categoryLookup.get("exterior-touring"), brandId: brandLookup.get("fieldline"), isFeatured: false, isNew: false, isActive: true },
  { name: "Fieldline Door Edge Guard Set", slug: "fieldline-door-edge-guard-set", sku: "ZM-FLD-1320", shortDescription: "A flexible trim set for helping protect common door-edge contact points.", description: "A simple cut-to-length protective strip for everyday parking spaces and tighter garage access.", specifications: { VehicleExamples: "Universal door edges", Length: "5 metres", Fit: "Cut-to-length", Finish: "Low-profile black" }, price: "12.00", compareAtPrice: null, stockQuantity: 96, imageUrl: media.utility, categoryId: categoryLookup.get("exterior-touring"), brandId: brandLookup.get("fieldline"), isFeatured: false, isNew: false, isActive: true },
  { name: "Fieldline Roof Tie-Down Set", slug: "fieldline-roof-tie-down-set", sku: "ZM-FLD-1330", shortDescription: "A two-strap set for securing compatible touring loads.", description: "A practical strap set supplied with a storage pouch for compatible roof and cargo setups.", specifications: { VehicleExamples: "Compatible roof-rack systems", Contents: "Two straps", Length: "3 metres each", Storage: "Carry pouch" }, price: "26.00", compareAtPrice: null, stockQuantity: 39, imageUrl: media.utility, categoryId: categoryLookup.get("exterior-touring"), brandId: brandLookup.get("fieldline"), isFeatured: false, isNew: true, isActive: true },
  { name: "Fieldline Mud Guard Pair", slug: "fieldline-mud-guard-pair", sku: "ZM-FLD-1340", shortDescription: "A universal flexible guard pair for road spray and light debris.", description: "A practical pair of guards for drivers who want a more protected lower-body finish on everyday routes.", specifications: { VehicleExamples: "Cars and compact SUVs", Material: "Flexible rubber", Contents: "Pair", Finish: "Matte black" }, price: "28.00", compareAtPrice: null, stockQuantity: 46, imageUrl: media.utility, categoryId: categoryLookup.get("exterior-touring"), brandId: brandLookup.get("fieldline"), isFeatured: false, isNew: false, isActive: true },
  { name: "Vela Universal Dash Mount", slug: "vela-universal-dash-mount", sku: "ZM-VEL-1350", shortDescription: "An adjustable dashboard mount for phone-based navigation.", description: "A stable adjustable mount that keeps navigation in view while leaving the windscreen clear.", specifications: { VehicleExamples: "Most smartphones", Rotation: "360-degree", Mount: "Dashboard adhesive", Grip: "Adjustable arms" }, price: "24.00", compareAtPrice: null, stockQuantity: 88, imageUrl: media.mount, categoryId: categoryLookup.get("phone-navigation"), brandId: brandLookup.get("velaworks"), isFeatured: false, isNew: true, isActive: true },
  { name: "Vela Cable Management Clips", slug: "vela-cable-management-clips", sku: "ZM-VEL-1360", shortDescription: "A small clip set for tidier charging and navigation cables.", description: "A practical set of clips that reduces cable movement around the dashboard and console.", specifications: { VehicleExamples: "Universal cabin accessory", Contents: "Six clips", Mount: "Adhesive base", Finish: "Matte black" }, price: "8.00", compareAtPrice: null, stockQuantity: 130, imageUrl: media.mount, categoryId: categoryLookup.get("phone-navigation"), brandId: brandLookup.get("velaworks"), isFeatured: false, isNew: false, isActive: true },
  { name: "Vela Driving Screen Shade", slug: "vela-driving-screen-shade", sku: "ZM-VEL-1370", shortDescription: "A small visor that helps reduce direct glare on compatible navigation screens.", description: "A compact shade designed to improve screen visibility in brighter conditions without a bulky installation.", specifications: { VehicleExamples: "Compatible 7–9 inch screens", Fit: "Clip-on", Finish: "Low-reflection", Material: "ABS polymer" }, price: "15.00", compareAtPrice: null, stockQuantity: 62, imageUrl: media.mount, categoryId: categoryLookup.get("phone-navigation"), brandId: brandLookup.get("velaworks"), isFeatured: false, isNew: false, isActive: true },
  { name: "Vela Magnetic Vent Mount Pro", slug: "vela-magnetic-vent-mount-pro", sku: "ZM-VEL-1380", shortDescription: "A stronger magnetic vent mount for compact phone navigation.", description: "A revised vent mount with a metal clip and a firm magnetic surface for everyday use.", specifications: { VehicleExamples: "Most horizontal vents", Mount: "Magnetic vent clip", Rotation: "360-degree", Included: "Slim ring" }, price: "22.00", compareAtPrice: null, stockQuantity: 75, imageUrl: media.mount, categoryId: categoryLookup.get("phone-navigation"), brandId: brandLookup.get("velaworks"), isFeatured: true, isNew: false, isActive: true },
  { name: "Vela Navigation Charge Cable", slug: "vela-navigation-charge-cable", sku: "ZM-VEL-1390", shortDescription: "A low-profile USB-C cable for tidy dashboard charging.", description: "A durable cable in a useful length for connecting a navigation phone without excess slack.", specifications: { VehicleExamples: "USB-C compatible devices", Length: "1.2 metres", Connector: "USB-C", Finish: "Braided cable" }, price: "10.00", compareAtPrice: null, stockQuantity: 122, imageUrl: media.mount, categoryId: categoryLookup.get("phone-navigation"), brandId: brandLookup.get("velaworks"), isFeatured: false, isNew: true, isActive: true },
  { name: "Roadwell Socket Tool Roll", slug: "roadwell-socket-tool-roll", sku: "ZM-RDW-1400", shortDescription: "A tidy compact tool roll for a prepared garage or touring kit.", description: "A useful fabric roll with common small sockets and a space-saving storage layout.", specifications: { VehicleExamples: "Garage and touring use", Contents: "Metric sockets", Storage: "Tool roll", Handle: "Carry loop" }, price: "42.00", compareAtPrice: "49.00", stockQuantity: 37, imageUrl: media.inflator, categoryId: categoryLookup.get("workshop-tools"), brandId: brandLookup.get("roadwell"), isFeatured: true, isNew: true, isActive: true },
  { name: "Roadwell Trim Tool Set", slug: "roadwell-trim-tool-set", sku: "ZM-RDW-1410", shortDescription: "A non-marking tool set for compatible trim and interior adjustments.", description: "A compact set of polymer tools suited to careful interior and panel work.", specifications: { VehicleExamples: "Universal trim work", Contents: "Five tools", Material: "Non-marking polymer", Storage: "Slim pouch" }, price: "18.00", compareAtPrice: null, stockQuantity: 65, imageUrl: media.inflator, categoryId: categoryLookup.get("workshop-tools"), brandId: brandLookup.get("roadwell"), isFeatured: false, isNew: false, isActive: true },
  { name: "Roadwell Folding Work Mat", slug: "roadwell-folding-work-mat", sku: "ZM-RDW-1420", shortDescription: "A foldable kneeling mat for quick garage and roadside checks.", description: "A lightweight foam mat that folds down small between use and protects knees on hard ground.", specifications: { VehicleExamples: "Garage and roadside use", Material: "Closed-cell foam", Format: "Foldable", Care: "Wipe-clean" }, price: "20.00", compareAtPrice: null, stockQuantity: 56, imageUrl: media.inflator, categoryId: categoryLookup.get("workshop-tools"), brandId: brandLookup.get("roadwell"), isFeatured: false, isNew: false, isActive: true },
  { name: "Roadwell Compact Torque Wrench", slug: "roadwell-compact-torque-wrench", sku: "ZM-RDW-1430", shortDescription: "A compact adjustable wrench for compatible maintenance tasks.", description: "A well-balanced hand tool designed for a tidy home-garage toolkit.", specifications: { VehicleExamples: "Garage maintenance use", Drive: "3/8 inch", Range: "20–110Nm", Storage: "Protective case" }, price: "54.00", compareAtPrice: null, stockQuantity: 24, imageUrl: media.inflator, categoryId: categoryLookup.get("workshop-tools"), brandId: brandLookup.get("roadwell"), isFeatured: true, isNew: false, isActive: true },
  { name: "Roadwell Micro Repair Kit", slug: "roadwell-micro-repair-kit", sku: "ZM-RDW-1440", shortDescription: "A compact essentials kit for small fixes in the garage or on a trip.", description: "A portable kit with common small fasteners and hand tools for practical quick fixes.", specifications: { VehicleExamples: "Universal emergency kit", Contents: "Small tools and fasteners", Storage: "Hard case", Use: "Minor repairs" }, price: "33.00", compareAtPrice: null, stockQuantity: 44, imageUrl: media.inflator, categoryId: categoryLookup.get("workshop-tools"), brandId: brandLookup.get("roadwell"), isFeatured: false, isNew: true, isActive: true },
  { name: "Kintra Winter Visibility Pack", slug: "kintra-winter-visibility-pack", sku: "ZM-KIN-1450", shortDescription: "A compact seasonal kit for frosty mornings and low-visibility conditions.", description: "A useful seasonal bundle with a scraper, microfiber cloth and visibility-ready essentials.", specifications: { VehicleExamples: "UK and European winter driving", Contents: "Three-piece kit", Storage: "Compact pouch", Use: "Cold mornings" }, price: "19.00", compareAtPrice: null, stockQuantity: 82, imageUrl: media.utility, categoryId: categoryLookup.get("seasonal-essentials"), brandId: brandLookup.get("kintra"), isFeatured: true, isNew: true, isActive: true },
  { name: "Kintra Windshield Cover", slug: "kintra-windshield-cover", sku: "ZM-KIN-1460", shortDescription: "A folding windscreen cover for colder parked mornings.", description: "A simple protective cover that helps make morning starts a little more straightforward.", specifications: { VehicleExamples: "Sedans, SUVs and hatchbacks", Mount: "Door-flap tabs", Storage: "Carry sleeve", Use: "Frost and sun" }, price: "17.00", compareAtPrice: null, stockQuantity: 74, imageUrl: media.utility, categoryId: categoryLookup.get("seasonal-essentials"), brandId: brandLookup.get("kintra"), isFeatured: false, isNew: false, isActive: true },
  { name: "Kintra Vent Sunshade", slug: "kintra-vent-sunshade", sku: "ZM-KIN-1470", shortDescription: "A lightweight sunshade for hotter parking and road-trip stops.", description: "A simple folding shade designed to help keep direct cabin heat more manageable.", specifications: { VehicleExamples: "Universal windscreen fit", Format: "Accordion fold", Finish: "Reflective", Storage: "Slim strap" }, price: "15.00", compareAtPrice: null, stockQuantity: 91, imageUrl: media.utility, categoryId: categoryLookup.get("seasonal-essentials"), brandId: brandLookup.get("kintra"), isFeatured: false, isNew: true, isActive: true },
  { name: "Kintra Boot Weather Kit", slug: "kintra-boot-weather-kit", sku: "ZM-KIN-1480", shortDescription: "A compact carry kit for wet-weather drives and muddy stops.", description: "A simple boot kit with a reusable towel, protective gloves and a washable storage bag.", specifications: { VehicleExamples: "Universal boot kit", Contents: "Three practical pieces", Bag: "Water-resistant", Use: "Wet-weather travel" }, price: "26.00", compareAtPrice: null, stockQuantity: 55, imageUrl: media.utility, categoryId: categoryLookup.get("seasonal-essentials"), brandId: brandLookup.get("kintra"), isFeatured: false, isNew: false, isActive: true },
  { name: "Kintra Anti-Fog Cloth Set", slug: "kintra-anti-fog-cloth-set", sku: "ZM-KIN-1490", shortDescription: "A reusable cloth pair for routine interior-glass care.", description: "A compact cloth set designed for keeping interior glass clearer during damp or cold conditions.", specifications: { VehicleExamples: "Universal interior glass", Contents: "Two cloths", Care: "Machine washable", Use: "Interior visibility" }, price: "9.00", compareAtPrice: null, stockQuantity: 118, imageUrl: media.detailKit, categoryId: categoryLookup.get("seasonal-essentials"), brandId: brandLookup.get("kintra"), isFeatured: false, isNew: true, isActive: true },
];

for (const product of [...productRows, ...expandedProductRows]) await db.insert(products).values(product).onDuplicateKeyUpdate({ set: product });

console.log(`Seeded ${categoryRows.length} categories, ${brandRows.length} brands, and ${productRows.length + expandedProductRows.length} products.`);
